### ISSUE TITLE
Unexpected error during the creation of the csr/operator-minio-operator-csr: the server could not find the requested resource

### ISSUE THREAD

**Issue by nhha1602** [minio/operator#729] opened 2021-07-16 09:52 UTC
I just deployed minio-operator but got below error in minio-operator

[k8suser@ai-installsrv01 minio-tenant]$ kubectl logs minio-operator-788f586f8b-wgslg -n minio-operator
I0716 09:43:31.333822       1 main.go:74] Starting MinIO Operator
I0716 09:43:32.200381       1 main.go:146] caBundle on CRD updated
I0716 09:43:32.201219       1 main-controller.go:268] Setting up event handlers
I0716 09:43:32.201311       1 main-controller.go:665] Starting Tenant controller
I0716 09:43:32.201322       1 main-controller.go:668] Waiting for informer caches to sync
I0716 09:43:32.236159       1 main-controller.go:625] operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)
E0716 09:43:32.252894       1 operator.go:130] Unexpected error during the creation of the csr/operator-minio-operator-csr: the server could not find the requested resource
I0716 09:43:32.252917       1 main-controller.go:627] Waiting for the operator certificates to be issued the server could not find the requested resource
I0716 09:43:32.301934       1 main-controller.go:673] Starting workers
E0716 09:43:37.305905       1 main-controller.go:754] error syncing 'minio-dev/minio-dev': secrets "operator-tls" not found
I0716 09:43:42.265489       1 main-controller.go:625] operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)
E0716 09:43:42.271028       1 operator.go:130] Unexpected error during the creation of the csr/operator-minio-operator-csr: the server could not find the requested resource
I0716 09:43:42.271049       1 main-controller.go:627] Waiting for the operator certificates to be issued the server could not find the requested resource
E0716 09:43:47.387227       1 main-controller.go:754] error syncing 'minio-dev/minio-dev': secrets "operator-tls" not found
I0716 09:43:52.281509       1 main-controller.go:625] operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)
E0716 09:43:52.286457       1 operator.go:130] Unexpected error during the creation of the csr/operator-minio-operator-csr: the server could not find the requested resource
I0716 09:43:52.286488       1 main-controller.go:627] Waiting for the operator certificates to be issued the server could not find the requested resource
I0716 09:44:02.297720       1 main-controller.go:625] operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)
E0716 09:44:02.303359       1 operator.go:130] Unexpected error during the creation of the csr/operator-minio-operator-csr: the server could not find the requested resource
I0716 09:44:02.303384       1 main-controller.go:627] Waiting for the operator certificates to be issued the server could not find the requested resource
[k8suser@ai-installsrv01 minio-tenant]$ 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

[k8suser@ai-installsrv01 minio-tenant]$ kubectl get csr
No resources found
[k8suser@ai-installsrv01 minio-tenant]$ kubectl get secrets -n minio-dev
NAME                       TYPE                                  DATA   AGE
default-token-svvvn        kubernetes.io/service-account-token   3      52m
istio.default              istio.io/key-and-cert                 3      52m
minio-dev-console-secret   Opaque                                2      51m
minio-dev-secret           Opaque                                2      51m
minio-dev-user-0           Opaque                                2      51m
operator-webhook-secret    Opaque                                3      51m
[k8suser@ai-installsrv01 minio-tenant]$ kubectl get secrets -n minio-operator
NAME                         TYPE                                  DATA   AGE
console-sa-token-vt8s7       kubernetes.io/service-account-token   3      5h4m
default-token-c2gs6          kubernetes.io/service-account-token   3      7h23m
istio.console-sa             istio.io/key-and-cert                 3      5h4m
istio.default                istio.io/key-and-cert                 3      7h23m
istio.minio-operator         istio.io/key-and-cert                 3      5h4m
minio-operator-token-r6nsd   kubernetes.io/service-account-token   3      5h4m
[k8suser@ai-installsrv01 minio-tenant]$ 

## Your Environment

* Version used (`minio-operator`): 4.1.3
* Environment name and version (e.g. kubernetes v1.17.2):v1.17.2
* Server type and version:
* Operating System and version (`uname -a`): linux
* Link to your deployment file:

**Comment by nitisht** [comment] 2021-07-16 09:53
closing as duplicate of #720 . Please try the solution provided there and let us know if that works

**Closed by nitisht** 2021-07-16 09:53 UTC

**Comment by vadmeste** [comment] 2021-07-16 09:55
> Environment name and version (e.g. kubernetes v1.17.2):v1.17.2

@nitisht isn't Kubernetes here too old ?

**Comment by nitisht** [comment] 2021-07-16 10:09
> > Environment name and version (e.g. kubernetes v1.17.2):v1.17.2
> 
> @nitisht isn't Kubernetes here too old ?

Yes, @nhha1602 as per our docs, the minimum k8s version required is 1.19 ref: https://github.com/minio/operator#prerequisites
