### ISSUE TITLE
Tenant creation via Operator Console gets stuck in "Provisioning initial users"

### ISSUE THREAD

**Issue by realulim** [minio/operator#1605] opened 2023-05-12 14:22 UTC
## Expected Behavior
I want to create a tenant "mytenant" via the Operator Console.

## Current Behavior
Upon clicking "create" the operator gets stuck in the "Provisioning initial users" phase. The pods get stuck in "terminating". Don't be confused by the age numbers, they are continually reset to 0, so this is the state after waiting about 30 minutes:

```
NAME                   READY   STATUS        RESTARTS   AGE
mytenant-pool-0-0   0/2     Terminating   0          2s
mytenant-pool-0-1   0/2     Terminating   0          109s
mytenant-pool-0-2   0/2     Terminating   0          5s

```
The operator pod fails some kind of healthcheck according to its log:

```
I0512 14:05:08.698110       1 event.go:285] Event(v1.ObjectReference{Kind:"Tenant", Namespace:"minio", Name:"mytenant", UID:"54905f0d-1a26-48f4-88c4-d698dea936b1", APIVersion:"minio.min.io/v2", ResourceVersion:"322074", FieldPath:""}): type: 'Warning' reason: 'UsersCreatedFailed' Users creation failed: Put "https://minio.minio.svc.cluster.local/minio/admin/v3/add-user?accessKey=xxxxxxxxxxxxxxxxx": dial tcp 10.43.136.176:443: connect: connection refused
I0512 14:05:11.065919       1 monitoring.go:124] 'minio/mytenant' Failed to get cluster health: Get "https://minio.minio.svc.cluster.local/minio/health/cluster": dial tcp 10.43.136.176:443: connect: connection refused

```

## Steps to Reproduce (for bugs)
1. Install Operator via `curl -L https://github.com/minio/operator/releases/download/v5.0.4/kubectl-minio_5.0.4_linux_amd64 -o /usr/local/bin/kubectl-minio`
2. `kubectl minio init`
3. `kubectl minio proxy -n minio-operator`
4. Go to Web Console and create tenant

## Context
The environment is a multi-node K3s cluster, cert-manager is installed and working. The node-local volumes are actually created ok, but they are not attached to any pod. After deleting the tenant via `kubectl minio tenant delete mytenant -n minio` the PVCs and PVs remain, as well as the backing volumes.

## Your Environment

* Version used (`minio-operator`): v5.0.4
* Environment name and version (e.g. kubernetes v1.17.2): v1.24.13+k3s1
* Server type and version:
* Operating System and version (`uname -a`): Rocky Linux 9

**Comment by shtripat** [comment] 2023-06-21 10:12
Have you tried this with higher versions of k8s?
With v1.25.3 locally I don't see an issue and able to create tenant fine.

**Comment by realulim** [comment] 2023-06-21 16:48
I haven't tried it with any other K8s version, as the one I am using is explicitly supported (Kubernetes 1.21 or Later). Since I haven't done anything but run the installation scripts, there must be a bug in them that triggers in my case and not yours. The error message says that the healthcheck endpoint isn't reachable, therefore I think that MinIO hasn't come up at all.

**Comment by dvaldivia** [comment] 2023-06-27 00:13
Are you using upstream kubernetes 1.21? That problem you are describing could be due to a problem with TLS, which means the `CertificateSigningRequests` (or CSRs) Are not getting issued

**Comment by realulim** [comment] 2023-06-27 06:52
I am using v1.24.13+k3s1 (K3s). The Cert Manager seems to work fine in general, i. e. I can issue certificates for other purposes.

**Comment by cesnietor** [comment] 2023-07-17 17:04
We'll try to replicate it using that version.

**Comment by allanrogerr** [comment] 2023-10-11 20:03
@realulim am also unable to replicate the issue. Are you still facing this - If so, could you try creating a tenant without TLS or with Auto TLS; or consider trying a later version of k3s and k8s?

**Comment by realulim** [comment] 2023-10-12 07:07
I am now using another object store on this cluster, but when I start another project with a new cluster, I will try it again with the then current versions. Thank you for looking into it.

**Comment by allanrogerr** [comment] 2023-11-14 22:39
As a workaround, simply, try changing your `.spec.pools` podAntiAffinity to NOT schedule on tenants that are NOT your tenant and on pools that are NOT your pools. e.g.
```
  - affinity:                                    
      podAntiAffinity:                           
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:                               
            matchExpressions:                          
            - key: v1.min.io/tenant                    
              operator: NotIn                          
              values:                                  
              - myminio            
            - key: v1.min.io/pool  
              operator: NotIn      
              values:            
              - pool-0           
          topologyKey: kubernetes.io/hostname
```

I'm looking more into this.

**Comment by allanrogerr** [comment] 2023-11-14 22:44
@realulim @dankonino FYI

**Comment by houshym** [comment] 2023-11-19 07:12
I have the same issue:
Kubernetes version: Rancher RKE2  1.25.9
MInio OPerator Veriosn:  5.0.10   5.0.3

**Comment by allanrogerr** [comment] 2023-11-29 02:52
@a-h What is the output of:
```
kubectl version
k3s --version
```

**Comment by a-h** [comment] 2023-11-29 09:35
Thanks for looking into this @allanrogerr - happy to follow debug instructions etc.

`kubectl version`:

```
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.5+k3s1
```

`k3s` isn't present in my Linux machine path, I assume that Rancher Desktop (Version 1.11.0) takes care of that. When I use `rdctl` and access the VM that Rancher Desktop starts up, it has this version:

```
0 127 /home/adrian-hesketh % rdctl shell bash
/home/adrian-hesketh $ k3s
NAME:
   k3s - Kubernetes, but small and simple

USAGE:
   k3s [global options] command [command options] [arguments...]

VERSION:
   v1.27.5+k3s1 (8d074ecb)
```

**Comment by allanrogerr** [comment] 2023-11-29 11:21
@a-h Could you paste the output of `kubectl -n tenant-lite get tenant/<TENANT_NAME> -o yaml`?

**Comment by allanrogerr** [comment] 2023-11-29 11:45
Also, are you able to create the tenant using helm? An example is here: https://github.com/minio/operator/tree/master/helm/operator

**Comment by Yc-Chen** [comment] 2023-12-04 19:45
I'm having similar issue, also on rancher-desktop. I tried spinning up both from operator console and using helm chart.

With operator console, it's stuck with "Provisioning initial users". But I think this is further than helm chart.

With helm chart, it is stuck with provisioning persistent volume. I have installed this [local-path-provisioner](https://github.com/rancher/local-path-provisioner).

Rancher desktop version 1.9.0
Kubernetes version 1.27.3
chart minio-operator/operator version 5.0.11
chart minio-operator/tenant version 5.0.11

**Comment by allanrogerr** [comment] 2023-12-04 20:47
@Yc-Chen Could you paste the output of `kubectl -n tenant-lite get tenant/<TENANT_NAME> -o yaml`?

**Comment by Yc-Chen** [comment] 2023-12-05 09:25
I also saw this error from the minio tenant pod:

```
ERROR Unable to initialize backend: parity validation returned an error: parity 4 should be less than or equal to 0 <- (4, 1), for pool(1st)
```

**Comment by allanrogerr** [comment] 2023-12-05 12:36
> @a-h Could you paste the output of `kubectl -n tenant-lite get tenant/<TENANT_NAME> -o yaml`?

?

**Comment by allanrogerr** [comment] 2023-12-05 16:56
A 1-node cluster can still house several pods (servers) - there is no restriction. We are addressing the parity issue [here](https://github.com/minio/operator/issues/1900)

**Comment by allanrogerr** [comment] 2023-12-06 20:18
Also related https://github.com/minio/operator/pull/1902

**Comment by chingchien-wu** [comment] 2024-01-11 02:27
Hi All,

I am using web-ui to create tenant face the same issue.
`Users creation failed: Put "http://minio.minio.svc.cluster.local/minio/admin/v3/add-user?accessKey=oc1234567": dial tcp 10.109.68.133:80: connect: connection refused`
Instances:2  Clusters:1  Total Drives:4
k8s version : 1.28.3
MinIO version : 5.0.11

**Comment by cesnietor** [comment] 2024-02-12 17:54
closing due to innactivity. Please raise a new one with more steps/logs thanks.

**Closed by cesnietor** 2024-02-12 17:54 UTC
Labels: question, community, triage

**Comment by Alii2121** [comment] 2024-06-27 13:32
Can you check the operator logs for any `x509 Certificate signed by unknown authority_ errors`, I had the same issue and it was caused by the TLS Certificate created by the operator.

To test it try to create a tenant without the TLS option from the console under the Security parameters,

**Comment by a-h** [comment] 2024-06-27 14:06
Sorry, I gave up on the k8s operator. We run it on VMs instead.
