### ISSUE TITLE
"empty tenant credentials" after (potentially failed) upgrade

### ISSUE THREAD

**Issue by x3nb63** [minio/operator#1675] opened 2023-07-05 15:37 UTC
while having to work on directpv I accidentially upgraded minio from a quite old version, skipping many releases.

It probably was `RELEASE.2022-06-25T15-50-16Z` or a few before, going straight to `RELEASE.2023-06-29T05-12-28Z`.

## Current Behavior

The operator is running and considers itself fine as far as I see.

The tenant, however, does not come up. It says:
```
ERROR Unable to validate passed arguments in MINIO_ARGS:env+tls://<hash>@operator.minio-operator.svc.cluster.local:4222/webhook/v1/getenv/my-io/myio: Get "https://operator.minio-operator.svc.cluster.local:4222/webhook/v1/getenv/my-io/my?key=MINIO_ARGS": dial tcp 10.105.201.5:4222: i/o timeout
```
while the operator repeatedly says:

```
E0705 14:40:33.023804       1 monitoring.go:340] empty tenant credentials
E0705 14:40:33.023858       1 monitoring.go:310] error checking health check 'my-io/myio': empty tenant credentials
I0705 14:40:34.062540       1 event.go:285] Event(v1.ObjectReference{Kind:"Tenant", Namespace:"myio-io", Name:"myio", UID:"5ab33fdf-0636-4ef9-a9d0-ad562670333f", APIVersion:"minio.min.io/v2", ResourceVersion:"549875120", FieldPath:""}): type: 'Warning' reason: 'MissingCreds' Tenant is missing root credentials
E0705 14:40:44.640118       1 monitoring.go:340] empty tenant credentials
E0705 14:40:44.640165       1 monitoring.go:310] error checking health check 'my-io/myio': empty tenant credentials
E0705 14:40:45.595433       1 monitoring.go:78] empty tenant credentials
```

## Expected Behavior

Like to see what the actual problem is.

By looking up the error message from source code I figured it gets the credentials of `accesskey` and `secretkey` from a Secret object named `myio-secret` in the tenant namespace.

That secret exists and contains these keys with values. I dont see why it concludes they are empty?!  (the code checks for "").

As for the tenant trying to reach port 4222 of the operator service: I _assume_ this is cause its also thinking it has no credentials and then tries to obtain a cert, while this new version of operator does not serve anything on that port.

## Context

see above, the upgrade may have messed things - I am looking for a clue on what that might be.

## Your Environment

* Version used (`minio-operator`): v5.0.6
* Environment name and version: kubernetes v1.25.3
* Server type and version: CentOS Stream release 8, x86_64
* deployment done with `krew` + `kubectl minio init` ...

**Comment by jiuker** [comment] 2023-07-06 05:39
post the tenant @x3nb63

**Comment by x3nb63** [comment] 2023-07-06 09:02
here it is:

_(dont be too picky on "myio" and "my-io", I had to censor this for posting here ... for the keys I hope to change them later)_

```
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  creationTimestamp: "2022-06-10T11:09:04Z"
  generation: 9
  name: myio
  namespace: myio
  resourceVersion: "549875120"
  uid: 5ab33fdf-0636-4ef9-a9d0-ad562670303f
scheduler:
  name: ""
spec:
  certConfig:
    commonName: '*.myio-hl.myio-io.svc.cluster.local'
    dnsNames:
    - myio-pool-0-{0...1}.myio-hl.myio-io.svc.cluster.local
    organizationName:
    - system:nodes
  configuration:
    name: myio-env-configuration
  credsSecret:
    name: myio-secret
  env:
  - name: MINIO_PROMETHEUS_AUTH_TYPE
    value: public
  exposeServices:
    console: true
    minio: true
  image: minio:RELEASE.2023-06-29T05-12-28Z
  imagePullPolicy: IfNotPresent
  imagePullSecret: {}
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - myio
            - key: v1.min.io/pool
              operator: In
              values:
              - pool-1
          topologyKey: kubernetes.io/hostname
    name: pool-0
    resources: {}
    servers: 2
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "998579896320"
        storageClassName: direct-csi-min-io
      status: {}
    volumesPerServer: 4
  requestAutoCert: false
  users:
  - name: myio-user-0
status:
  availableReplicas: 0
  certificates:
    autoCertEnabled: true
  currentState: empty tenant credentials
  drivesOnline: 8
  healthMessage: Service Unavailable
  healthStatus: red
  pools:
  - legacySecurityContext: false
    ssName: myio-pool-0
    state: PoolInitialized
  provisionedUsers: true
  revision: 0
  syncVersion: v5.0.0
  usage:
    capacity: 3994319585280
    rawCapacity: 7988639170560
    rawUsage: 16621568
  writeQuorum: 5
```

```
apiVersion: v1
data:
  accesskey: "YmM0ZTYzZTg1ODlmM2EzYjJmNjc4Yzg0NWYyYWRmNTg="
  secretkey: "NjliYTNhZjYzY2E0Y2NlNmY2ZWEyODYzMzE2YWQ5Njk="
immutable: true
kind: Secret
metadata:
  creationTimestamp: "2022-06-10T11:09:04Z"
  labels:
    v1.min.io/tenant: myio
  name: myio-secret
  namespace: myio
  resourceVersion: "268648465"
  uid: a3f9522d-c8ee-4e62-b85a-f637765ccb0b
type: Opaque
```

**Comment by jiuker** [comment] 2023-07-06 09:05
@x3nb63 myio-env-configuration secret ?

**Comment by x3nb63** [comment] 2023-07-06 14:32
```
apiVersion: v1
data:
  config.env: ""
kind: Secret
metadata:
  creationTimestamp: "2022-06-13T09:42:32Z"
  labels:
    v1.min.io/tenant: myio
  name: myio-env-configuration
  namespace: myio
  resourceVersion: "271406010"
  uid: 95ee9ae0-3f9b-41b9-a729-c2f47b235798
type: Opaque
```

the `config.env` I had to take out. It only contains `export MINIO_IDENTITY_LDAP_*` variables to authenticate users against internal LDAP ... that always worked.

**Comment by jiuker** [comment] 2023-07-06 14:42
So its the problem here. No root user / password at this secret. @x3nb63

**Comment by x3nb63** [comment] 2023-07-06 14:59
all right, how is it supposed to look?

I guess this secret was/is/should-be created by the operator? So mine is probably old?

**Comment by jiuker** [comment] 2023-07-06 15:18
https://github.com/minio/operator/blob/master/helm/tenant/templates/tenant-configuration.yaml @x3nb63

**Comment by jiuker** [comment] 2023-07-07 00:40
@x3nb63 Everything is ok?

**Comment by x3nb63** [comment] 2023-07-07 09:19
sorry for the delay... 

adding MINIO_ROOT_USER and _PASSWORD got things moving, thanks! The operator changed to this output:

```
I0707 08:21:41.479543       1 monitoring.go:124] 'my-io/myio' Failed to get cluster health: Get "http://minio.my-io.svc.cluster.local/minio/health/cluster": dial tcp 10.110.41.2:80: i/o timeout
I0707 08:22:06.517096       1 main-controller.go:1089] my-io/myio is not running can't update image online
E0707 08:22:06.517164       1 main-controller.go:676] error syncing 'my-io/myio': MinIO is not ready
I0707 08:23:06.588444       1 main-controller.go:1089] my-io/myio is not running can't update image online
E0707 08:23:06.588502       1 main-controller.go:676] error syncing 'my-io/myio': MinIO is not ready
I0707 08:24:06.651584       1 main-controller.go:1089] dxinf-io/dxinf is not running can't update image online
E0707 08:24:06.651640       1 main-controller.go:676] error syncing 'my-io/myio': MinIO is not ready
...
< the last two lines repeat indefinitely now >
...
```

while the tenant pod reaches Running state and repeats this output:

```
2023-07-07T10:44:44.778835686+02:00 API: SYSTEM()
2023-07-07T10:44:44.778856864+02:00 Time: 08:44:44 UTC 07/07/2023
2023-07-07T10:44:44.778878650+02:00 DeploymentID: 711d8736-9600-45e5-a933-f0c79b8adf19
2023-07-07T10:44:44.778887398+02:00 Error: peer is not reachable (*errors.errorString)
2023-07-07T10:44:44.778896982+02:00        peerAddress="myio-pool-0-1.myio-hl.myio.svc.cluster.local:9000"
2023-07-07T10:44:44.778904670+02:00        5: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
2023-07-07T10:44:44.778962169+02:00        4: internal/logger/logonce.go:149:logger.LogOnceIf()
2023-07-07T10:44:44.778970169+02:00        3: cmd/notification.go:1127:cmd.(*NotificationSys).GetClusterMetrics()
2023-07-07T10:44:44.778976879+02:00        2: cmd/metrics-v2.go:2665:cmd.(*minioClusterCollector).Collect()
2023-07-07T10:44:44.778985187+02:00        1: github.com/prometheus/client_golang@v1.16.0/prometheus/registry.go:455:prometheus.(*Registry).Gather.func1()
2023-07-07T10:44:44.781537163+02:00
2023-07-07T10:44:44.781586912+02:00 API: SYSTEM()
2023-07-07T10:44:44.781603647+02:00 Time: 08:44:44 UTC 07/07/2023
2023-07-07T10:44:44.781619245+02:00 DeploymentID: 711d8736-9600-45e5-a933-f0c79b8adf19
2023-07-07T10:44:44.781636839+02:00 Error: peer is not reachable (*errors.errorString)
2023-07-07T10:44:44.781650129+02:00        peerAddress="myio-pool-0-1.myio-hl.myio.svc.cluster.local:9000"
2023-07-07T10:44:44.781659510+02:00        2: internal/logger/logger.go:258:logger.LogIf()
2023-07-07T10:44:44.781668725+02:00        1: cmd/notification.go:104:cmd.(*NotificationGroup).Go.func1()
2023-07-07T10:44:44.781714002+02:00
2023-07-07T10:44:44.781732571+02:00 API: SYSTEM()
2023-07-07T10:44:44.781741771+02:00 Time: 08:44:44 UTC 07/07/2023
2023-07-07T10:44:44.781766847+02:00 DeploymentID: 711d8736-9600-45e5-a933-f0c79b8adf19
2023-07-07T10:44:44.781785907+02:00 Error: peer is not reachable (*errors.errorString)
2023-07-07T10:44:44.781806389+02:00        peerAddress="myio-pool-0-1.myio-hl.myio.svc.cluster.local:9000"
2023-07-07T10:44:44.781818695+02:00        9: internal/logger/logger.go:258:logger.LogIf()
2023-07-07T10:44:44.781829010+02:00        8: cmd/notification.go:501:cmd.(*NotificationSys).GetClusterAllBucketStats()
2023-07-07T10:44:44.781836058+02:00        7: cmd/bucket-replication-stats.go:270:cmd.(*ReplicationStats).getAllLatest()
2023-07-07T10:44:44.781841484+02:00        6: cmd/metrics-v2.go:2069:cmd.getBucketUsageMetrics.func1()
2023-07-07T10:44:44.781847057+02:00        5: cmd/metrics-v2.go:268:cmd.(*MetricsGroup).RegisterRead.func1.1()
2023-07-07T10:44:44.781860039+02:00        4: cmd/utils.go:990:cmd.(*timedValue).Get()
2023-07-07T10:44:44.781894595+02:00        3: cmd/metrics-v2.go:298:cmd.(*MetricsGroup).Get()
2023-07-07T10:44:44.781905702+02:00        2: cmd/metrics-v2.go:2709:cmd.populateAndPublish()
2023-07-07T10:44:44.781911704+02:00        1: cmd/metrics-v2.go:2674:cmd.ReportMetrics.func1()
2023-07-07T10:44:48.054047572+02:00 Waiting for all MinIO IAM sub-system to be initialized.. possible cause (Storage resources are insufficient for the read operation .minio.sys/)
2023-07-07T10:44:50.428562945+02:00 Waiting for all MinIO IAM sub-system to be initialized.. possible cause (Storage resources are insufficient for the read operation .minio.sys/)
2023-07-07T10:44:51.431822692+02:00 Waiting for all MinIO IAM sub-system to be initialized.. possible cause (Storage resources are insufficient for the read operation .minio.sys/)
2023-07-07T10:44:51.797967922+02:00 Waiting for all MinIO IAM sub-system to be initialized.. possible cause (Storage resources are insufficient for the read operation .minio.sys/)
2023-07-07T10:44:53.665992082+02:00 Waiting for all MinIO IAM sub-system to be initialized.. possible cause (Storage resources are insufficient for the read operation .minio.sys/)
2023-07-07T10:44:54.139930143+02:00 Waiting for all MinIO IAM sub-system to be initialized.. possible cause (Storage resources are insufficient for the read operation .minio.sys/)
2023-07-07T10:44:57.124542040+02:00 Waiting for all MinIO IAM sub-system to be initialized.. possible cause (Storage resources are insufficient for the read operation .minio.sys/)
2023-07-07T10:44:59.871798808+02:00 Waiting for all MinIO IAM sub-system to be initialized.. possible cause (Storage resources are insufficient for the read operation .minio.sys/)
2023-07-07T10:45:03.775461941+02:00 Waiting for all MinIO IAM sub-system to be initialized.. possible cause (Storage resources are insufficient for the read operation .minio.sys/)
2023-07-07T10:45:05.098351486+02:00 Waiting for all MinIO IAM sub-system to be initialized.. possible cause (Storage resources are insufficient for the read operation .minio.sys/)
2023-07-07T10:45:07.095019811+02:00 Waiting for all MinIO IAM sub-system to be initialized.. possible cause (Storage resources are insufficient for the read operation .minio.sys/)
2023-07-07T10:45:07.979496565+02:00
```

I do not understand what its telling, whether that `.minio.sys/` is configuration related or not?

This log is from `myio-pool-0-0`, while a `myio-pool-0-1` pod existed once but now ceased to do so. (OR  was it a `myio-pool-1-0`?! - can't remember)

Note that missing disks may be involved here; half are definitely missing (that `myio-pool-0-1`, presumably), which the kubectl tool correctly states now:

```
$ kubectl minio tenant status myio
=====================
Pools:              1
Revision:           0
Sync version:       v5.0.0
Write quorum:       5
Health status:      red
Drives online:      4
Drives offline:     4
Drives healing:     0
Current status:     Initialized
Usable capacity:    3.6 TiB
Provisioned users:  true
Available replicas: 0
```

The 4 reported as online I am not so sure. .... this is what caused me to work in directpv initially, another "interesting" way of getting oneself stuck with storage:

Backplane in a machine died, but NOT the disks. The chassis got replaced, same model, CPUs + Memory + controller card got moved, same firmwares on new board and backplane afaict, BUT it rejects _some_ of the disks (not all) and disables their slots after some minutes....   since the disks themselves are OK (tested in another machine), I moved them to another node where they do not get rejected. 

The PVCs appear to have picked up, since that tenant pool is Running now and I see them mounted as `/export[0-3]` from its Pod-shell:

```
bash-4.4$ df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         111G   57G   55G  52% /
tmpfs            64M     0   64M   0% /dev
tmpfs            63G     0   63G   0% /sys/fs/cgroup
/dev/sdj        930G   18G  913G   2% /export0
/dev/sdh        930G   18G  913G   2% /export1
/dev/sdi        930G   18G  913G   2% /export2
/dev/sdg        930G   18G  913G   2% /export3
/dev/sda3       111G   57G   55G  52% /data
shm              64M     0   64M   0% /dev/shm
tmpfs           126G   12K  126G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs            63G     0   63G   0% /proc/acpi
tmpfs            63G     0   63G   0% /proc/scsi
tmpfs            63G     0   63G   0% /sys/firmware
``` 

To me it looks as if this is correct and all I need to do is adding a new pool with 4 new disks to that tenant so it can heal, right?

**Comment by jiuker** [comment] 2023-07-07 15:58
You should read document first. 2 node is a toy deployment. Close it for there is no issue or bug here.

**Closed by jiuker** 2023-07-07 15:58 UTC
Labels: community

**Comment by harshavardhana** [comment] 2023-07-07 16:56
> The 4 reported as online I am not so sure. .... this is what caused me to work in directpv initially, another "interesting" way of getting oneself stuck with storage:
> 
> Backplane in a machine died, but NOT the disks. The chassis got replaced, same model, CPUs + Memory + controller card got moved, same firmwares on new board and backplane afaict, BUT it rejects _some_ of the disks (not all) and disables their slots after some minutes.... since the disks themselves are OK (tested in another machine), I moved them to another node where they do not get rejected.
> 
> The PVCs appear to have picked up, since that tenant pool is Running now and I see them mounted as `/export[0-3]` from its Pod-shell:

With 2 node deployments, if you move the drives around like this and its actual mapping is lost. Then it is not possible for MinIO to read them. 

The issue is that drives are not in the same position anymore.
