### ISSUE TITLE
[log-search-api] CrashLoopBack - Error connecting to db: pq: password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by pjamenaja** [minio/operator#1275] opened 2022-09-01 23:01 UTC
## Steps to Reproduce (for bugs)

1. Create MinIO tenant as usual by YAML below, actually I used helm chart version 4.4.28 to render the tenant manifest.
```yml
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  labels:
    app: minio
  name: minio-soc
  namespace: minio-soc
spec:
  configuration:
    name: minio-admin-secret
  credsSecret:
    name: tenant-secret
  features:
    bucketDNS: false
  image: quay.io/minio/minio:RELEASE.2022-05-26T05-48-41Z
  imagePullPolicy: IfNotPresent
  log:
    affinity:
      nodeAffinity: {}
      podAffinity: {}
      podAntiAffinity: {}
    audit:
      diskCapacityGB: 1
    db:
      affinity:
        nodeAffinity: {}
        podAffinity: {}
        podAntiAffinity: {}
      image: ""
      initimage: ""
      securityContext:
        fsGroup: 999
        runAsGroup: 999
        runAsNonRoot: true
        runAsUser: 999
      serviceAccountName: ""
      tolerations: []
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: longhorn
    image: ""
    securityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    serviceAccountName: ""
    tolerations: []
  logging:
    anonymous: true
    json: true
    quiet: true
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
  - name: pool-0
    servers: 4
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
        storageClassName: longhorn
    volumesPerServer: 4
  prometheus:
    affinity:
      nodeAffinity: {}
      podAffinity: {}
      podAntiAffinity: {}
    diskCapacityGB: 1
    image: ""
    initimage: ""
    securityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    serviceAccountName: ""
    sidecarimage: ""
    storageClassName: longhorn
  prometheusOperator: false
  requestAutoCert: true
  subPath: /data
```
2. Delete the tenant using command `kubectl delete tenant minio-soc -n minio-soc`.
3. Create tenant again with the same manifest above, every pods started successfully except `log-search-api`  with error shown below.
> Error connecting to db: pq: password authentication failed for user "postgres"

## Your Environment

* Version used (`minio-operator`):
* Environment name and version (e.g. kubernetes v1.17.2):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by dvaldivia** [comment] 2022-09-01 23:40
hi @pjamenaja did you by deleted the tenant and it's secrets and re-created it and re-used the postgres PVC? if that's the case, the password is the same as the old one, in that case you'd need to exec into the postgres pod and change the default password, I think @pjuarezd has a code snippet to do it in one line

**Comment by pjuarezd** [comment] 2022-09-01 23:41
https://github.com/minio/operator/issues/1220#issuecomment-1222748409

**Comment by dvaldivia** [comment] 2022-09-01 23:41
try
```bash
NS=minio-tenant-1
TENANT_NAME=minio-tenant-1
kubectl exec -n $NS ${TENANT_NAME}-log-0 -c log-search-pg -- psql -U postgres -c "ALTER USER postgres WITH PASSWORD '$(kubectl get secret -n $NS ${TENANT_NAME}-log-secret -o jsonpath={.data.POSTGRES_PASSWORD} | base64 --decode)';"
```

**Comment by pjamenaja** [comment] 2022-09-02 02:01
Thanks a lot. That resolved my issue.

**Comment by pjuarezd** [comment] 2022-09-06 16:23
Duplicate of #1239

**Closed by pjuarezd** 2022-09-06 16:23 UTC
Labels: duplicate, community, triage
