### ISSUE TITLE
Waiting for a minimum of 8 drives to come online (elapsed 12s)

### ISSUE THREAD

**Issue by sathishkumar-p** [minio/operator#1913] opened 2023-12-17 08:45 UTC
Hi,
I have deployed the minio in distributed mode using minio operator. When I trying to expand the pool. I am getting the following error:
**Waiting for a minimum of 8 drives to come online (elapsed 12s)**
I have nearly, waited for **3 hours** for all pods get sync, but not work so reverted to the previous pool size.

## Expected Behavior
The extra pool should added and the size of minio cluster should expanded.

## Current Behavior
Failed to expand due to minimum drivers not coming online.

## Steps to Reproduce (for bugs)
1. Setup a minio disturbed cluster using the minio operator with 3 three pools, per pool 4 servers, and 4 drivers each of 100 Gi
2. Add an extra pool-4, pods keep on restarting, not come online for 3 hours.

## Context
This is my production environment. Now we are reaching the size limit. We are unable to expand it.

## Regression
 No
  quay.io/minio/operator:v5.0.6

## Your Environment

* Version used (`minio-operator`): quay.io/minio/operator:v5.0.6
* Environment name and version (e.g. kubernetes v1.17.2):  v1.26.10
* Server type and version: Disturbed and  RELEASE.2023-08-31T15-31-16Z
* Operating System and version (`uname -a`):
* Link to your deployment file: Linux minio-pool-1-0 5.15.0-89-generic #99~20.04.1-Ubuntu SMP Thu Nov 2 15:16:47 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Complete: Error Log :
` "level":"ERROR","errKind":"ALL","time":"2023-12-17T04:43:31.98244083Z","api":{"name":"SYSTEM","args":{"bucket":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","object":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5"}},"remotehost":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","error":{"message":"*fmt.wrapError","source":["internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()","internal/logger/logonce.go:149:logger.LogOnceIf()","internal/rest/client.go:319:rest.(*Client).Call()","cmd/storage-rest-client.go:167:cmd.(*storageRESTClient).call()","cmd/storage-rest-client.go:567:cmd.(*storageRESTClient).ReadAll()","cmd/format-erasure.go:391:cmd.loadFormatErasure()","cmd/format-erasure.go:327:cmd.loadFormatErasureAll.func1()","github.com/minio/pkg@v1.7.5/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()"]}}
{"level":"ERROR","errKind":"ALL","time":"2023-12-17T04:43:31.98268901Z","api":{"name":"SYSTEM","args":{"bucket":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","object":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5"}},"remotehost":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","error":{"message":"*fmt.wrapError","source":["internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()","internal/logger/logonce.go:149:logger.LogOnceIf()","internal/rest/client.go:319:rest.(*Client).Call()","cmd/storage-rest-client.go:167:cmd.(*storageRESTClient).call()","cmd/storage-rest-client.go:567:cmd.(*storageRESTClient).ReadAll()","cmd/format-erasure.go:391:cmd.loadFormatErasure()","cmd/format-erasure.go:327:cmd.loadFormatErasureAll.func1()","github.com/minio/pkg@v1.7.5/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()"]}}
{"level":"ERROR","errKind":"ALL","time":"2023-12-17T04:43:31.982752021Z","api":{"name":"SYSTEM","args":{"bucket":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","object":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5"}},"remotehost":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","error":{"message":"*fmt.wrapError","source":["internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()","internal/logger/logonce.go:149:logger.LogOnceIf()","internal/rest/client.go:319:rest.(*Client).Call()","cmd/storage-rest-client.go:167:cmd.(*storageRESTClient).call()","cmd/storage-rest-client.go:567:cmd.(*storageRESTClient).ReadAll()","cmd/format-erasure.go:391:cmd.loadFormatErasure()","cmd/format-erasure.go:327:cmd.loadFormatErasureAll.func1()","github.com/minio/pkg@v1.7.5/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()"]}}
{"level":"ERROR","errKind":"ALL","time":"2023-12-17T04:43:31.98295671Z","api":{"name":"SYSTEM","args":{"bucket":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","object":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5"}},"remotehost":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","error":{"message":"*fmt.wrapError","source":["internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()","internal/logger/logonce.go:149:logger.LogOnceIf()","internal/rest/client.go:319:rest.(*Client).Call()","cmd/storage-rest-client.go:167:cmd.(*storageRESTClient).call()","cmd/storage-rest-client.go:567:cmd.(*storageRESTClient).ReadAll()","cmd/format-erasure.go:391:cmd.loadFormatErasure()","cmd/format-erasure.go:327:cmd.loadFormatErasureAll.func1()","github.com/minio/pkg@v1.7.5/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()"]}}
{"level":"ERROR","errKind":"ALL","time":"2023-12-17T04:43:31.982946786Z","api":{"name":"SYSTEM","args":{"bucket":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","object":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5"}},"remotehost":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","error":{"message":"*fmt.wrapError","source":["internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()","internal/logger/logonce.go:149:logger.LogOnceIf()","internal/rest/client.go:319:rest.(*Client).Call()","cmd/storage-rest-client.go:167:cmd.(*storageRESTClient).call()","cmd/storage-rest-client.go:567:cmd.(*storageRESTClient).ReadAll()","cmd/format-erasure.go:391:cmd.loadFormatErasure()","cmd/format-erasure.go:327:cmd.loadFormatErasureAll.func1()","github.com/minio/pkg@v1.7.5/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()"]}}
{"level":"ERROR","errKind":"ALL","time":"2023-12-17T04:43:31.990843037Z","api":{"name":"SYSTEM","args":{"bucket":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","object":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5"}},"remotehost":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","error":{"message":"*fmt.wrapError","source":["internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()","internal/logger/logonce.go:149:logger.LogOnceIf()","internal/rest/client.go:319:rest.(*Client).Call()","cmd/storage-rest-client.go:167:cmd.(*storageRESTClient).call()","cmd/storage-rest-client.go:567:cmd.(*storageRESTClient).ReadAll()","cmd/format-erasure.go:391:cmd.loadFormatErasure()","cmd/format-erasure.go:327:cmd.loadFormatErasureAll.func1()","github.com/minio/pkg@v1.7.5/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()"]}}
{"level":"ERROR","errKind":"ALL","time":"2023-12-17T04:43:31.991756289Z","api":{"name":"SYSTEM","args":{"bucket":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","object":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5"}},"remotehost":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","error":{"message":"*fmt.wrapError","source":["internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()","internal/logger/logonce.go:149:logger.LogOnceIf()","internal/rest/client.go:319:rest.(*Client).Call()","cmd/storage-rest-client.go:167:cmd.(*storageRESTClient).call()","cmd/storage-rest-client.go:567:cmd.(*storageRESTClient).ReadAll()","cmd/format-erasure.go:391:cmd.loadFormatErasure()","cmd/format-erasure.go:327:cmd.loadFormatErasureAll.func1()","github.com/minio/pkg@v1.7.5/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()"]}}
{"level":"ERROR","errKind":"ALL","time":"2023-12-17T04:43:31.9971456Z","api":{"name":"SYSTEM","args":{"bucket":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","object":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5"}},"remotehost":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","error":{"message":"*errors.errorString","source":["internal/logger/logger.go:258:logger.LogIf()","cmd/prepare-storage.go:254:cmd.connectLoadInitFormats()","cmd/prepare-storage.go:312:cmd.waitForFormatErasure()","cmd/erasure-server-pool.go:103:cmd.newErasureServerPools()","cmd/server-main.go:957:cmd.newObjectLayer()","cmd/server-main.go:704:cmd.serverMain.func9()","cmd/server-main.go:423:cmd.bootstrapTrace()","cmd/server-main.go:702:cmd.serverMain()"]}}
{"level":"INFO","errKind":"","time":"2023-12-17T04:43:31.997294634Z","message":"Waiting for a minimum of 8 drives to come online (elapsed 12s)\n"}`

**Comment by harshavardhana** [comment] 2023-12-17 09:43
@sathishkumar-p turn-off anonymous logging in the tenant deployment spec and share the actual logs.

**Comment by sathishkumar-p** [comment] 2023-12-18 04:33
Sure, let me do it

**Comment by sathishkumar-p** [comment] 2023-12-22 05:36
Hello @harshavardhana ,
Here are the logs after disabling the anonymous log:
FYI, Whenever i try to expand the size by adding pools the issue. The minio pods restart a lot of time and takes while to come back, but this time it taking more than 3 hrs but not back to online.
[
[Uploading minio-pool-0-3.log…]()
](url)

**Comment by allanrogerr** [comment] 2023-12-31 17:03
1.- Was expansion performed using the Console UI, `kubectl minio` or some other means?

2.- Was this tested successfully  on a lower environment before moving to production?

3.- Please provide the pod logs for one pod from each of the original 3 pools, as well as for one pod from the expansion pool. e.g. `kubectl -n <namespace> logs pod/minio-pool-0-3 > minio-pool-0-3.log`

4.- The logs provided seem to replication related. However replication was not mentioned in the original description. Note that there have been several important fixes to replication since minio RELEASE.2023-08-31T15-31-16Z. When do you plan to upgrade.

**Comment by sathishkumar-p** [comment] 2024-01-01 02:56
Hi, @allanrogerr

1. Replication is performed using the helm tenant chart. I have added a new pool to the chart and argocd will do a sync.
2. Yes, I have acted many times. both env without any problem 
3. Since its production, I worried about bringing it down many times. Will it be fine to perform in a lower environment (replicating the issue)?
4. What is the stable version, not the latest version? Last time i have a garbage collection issue. Also Minio support suggested using the latest one not a stable one.

**Comment by sathishkumar-p** [comment] 2024-01-01 02:59
Node Expansion using helm chart of ' A Helm chart for MinIO Operator' tenant
`    - servers: 4
      ## Custom name for the pool
      name: pool-6
      ## volumesPerServer specifies the number of volumes attached per MinIO Tenant Pod / Server.
      volumesPerServer: 4
      ## size specifies the capacity per volume
      size: 200Mi
      ## storageClass specifies the storage class name to be used for this pool
      storageClassName: cinder-retain
      ## Used to specify annotations for pods
      annotations: { }
      ## Used to specify labels for pods
      labels: { }
      ## Used to specify a toleration for a pod
      tolerations: [ ]
      ## nodeSelector parameters for MinIO Pods. It specifies a map of key-value pairs. For the pod to be
      ## eligible to run on a node, the node must have each of the
      ## indicated key-value pairs as labels.
      ## Read more here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
      nodeSelector: { }
      ## Affinity settings for MinIO pods. Read more about affinity
      ## here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity.
      affinity: { }
      ## Configure resource requests and limits for MinIO containers
      resources:
        limits:
          cpu: 2000m
          memory: 1000Mi
        requests:
          cpu: 1500m
          memory: 700Mi       
      ## Configure security context
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
      ## Configure container security context
      containerSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      ## Configure topology constraints
      topologySpreadConstraints: [ ]
      ## Configure Runtime Class
      # runtimeClassName: ""  `

**Comment by sathishkumar-p** [comment] 2024-01-04 04:14
Hi @harshavardhana  and @allanrogerr,
Please let me know if you required additional information

**Comment by allanrogerr** [comment] 2024-01-04 13:55
@sathishkumar-p 
I believe you meant to say _Expansion is performed using the helm tenant chart_
It is best to reproduce the issue on a test environment first.
The latest stable version is RELEASE.2024-01-01T16-36-33Z as reported on https://min.io/docs/minio/linux/index.html

Still pending is the following:
Please provide the pod logs for one pod from each of the original 3 pools, as well as for one pod from the expansion pool. e.g. kubectl -n <namespace> logs pod/minio-pool-0-3 > minio-pool-0-3.log

**Comment by sathishkumar-p** [comment] 2024-01-05 05:05
@allanrogerr,
I'm trying to reproduce the issue in a lower environment as well as prod. I will provide the logs and also upgrade the version of minio and operator

**Comment by jiuker** [comment] 2024-01-08 03:11
@sathishkumar-p Is there a new deploy will restart? And stuck there?

**Comment by sathishkumar-p** [comment] 2024-01-08 05:43
Yes its restating @jiuker

**Comment by sathishkumar-p** [comment] 2024-01-08 05:45
@allanrogerr  and @harshavardhana 
Here I have reproduced the issue in a lower environment. The last 2 days have kept on restarting and not come online till now.
Logs which you asked as per the format:
[minio-pool-2-0.log](https://github.com/minio/operator/files/13856555/minio-pool-2-0.log)
[minio-pool-3-0.log](https://github.com/minio/operator/files/13856556/minio-pool-3-0.log)
[minio-pool-1-0.log](https://github.com/minio/operator/files/13856557/minio-pool-1-0.log)
[minio-pool-0-0.log](https://github.com/minio/operator/files/13856558/minio-pool-0-0.log)
[minio-pool-4-0.log](https://github.com/minio/operator/files/13856559/minio-pool-4-0.log)

**Comment by jiuker** [comment] 2024-01-08 07:32
> @allanrogerr and @harshavardhana Here I have reproduced the issue in a lower environment. The last 2 days have kept on restarting and not come online till now. Logs which you asked as per the format: [minio-pool-2-0.log](https://github.com/minio/operator/files/13856555/minio-pool-2-0.log) [minio-pool-3-0.log](https://github.com/minio/operator/files/13856556/minio-pool-3-0.log) [minio-pool-1-0.log](https://github.com/minio/operator/files/13856557/minio-pool-1-0.log) [minio-pool-0-0.log](https://github.com/minio/operator/files/13856558/minio-pool-0-0.log) [minio-pool-4-0.log](https://github.com/minio/operator/files/13856559/minio-pool-4-0.log)
> 
> ![image](https://private-user-images.githubusercontent.com/25504642/294819892-abc9f5b5-0917-46a4-9b38-31de09b90ea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTc5ODUsIm5iZiI6MTcwNDY5NzY4NSwicGF0aCI6Ii8yNTUwNDY0Mi8yOTQ4MTk4OTItYWJjOWY1YjUtMDkxNy00NmE0LTliMzgtMzFkZTA5YjkwZWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA3MDgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4MTZlMzBhMTY0ZDdkYTQyNDQ5NTdhNDExMmFjOWQ1MDIxZTI2MGM2NjZkMjcwYWVjNWM4YTJmMTJiYzFiMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C_-WFNW7jomU4JBuMrorw5zTrAAv5mX3Q31oJkAVgqs)

Could you retry this with latest version？

**Comment by JasperWey** [comment] 2024-01-08 09:23
I met the same problem, log like:
```bash
API: SYSTEM()
Time: 09:15:25 UTC 01/08/2024
Error: Read failed. Insufficient number of drives online (*errors.errorString)
       8: internal/logger/logger.go:258:logger.LogIf()
       7: cmd/prepare-storage.go:254:cmd.connectLoadInitFormats()
       6: cmd/prepare-storage.go:312:cmd.waitForFormatErasure()
       5: cmd/erasure-server-pool.go:104:cmd.newErasureServerPools()
       4: cmd/server-main.go:976:cmd.newObjectLayer()
       3: cmd/server-main.go:718:cmd.serverMain.func9()
       2: cmd/server-main.go:434:cmd.bootstrapTrace()
       1: cmd/server-main.go:716:cmd.serverMain()
Waiting for a minimum of 8 drives to come online (elapsed 21m31s)


API: SYSTEM()
Time: 09:15:26 UTC 01/08/2024
Error: Read failed. Insufficient number of drives online (*errors.errorString)
       8: internal/logger/logger.go:258:logger.LogIf()
       7: cmd/prepare-storage.go:254:cmd.connectLoadInitFormats()
       6: cmd/prepare-storage.go:312:cmd.waitForFormatErasure()
       5: cmd/erasure-server-pool.go:104:cmd.newErasureServerPools()
       4: cmd/server-main.go:976:cmd.newObjectLayer()
       3: cmd/server-main.go:718:cmd.serverMain.func9()
       2: cmd/server-main.go:434:cmd.bootstrapTrace()
       1: cmd/server-main.go:716:cmd.serverMain()
Waiting for a minimum of 8 drives to come online (elapsed 21m32s)

[root@node-136 minio]# k get po -n minio
NAME               READY   STATUS    RESTARTS   AGE
myminio-pool-0-0   2/2     Running   0          17m
myminio-pool-0-1   2/2     Running   0          17m
myminio-pool-0-2   2/2     Running   0          17m
myminio-pool-0-3   2/2     Running   0          17m

```


minio version:
1. operator: v5.0.11
2. minio: RELEASE.2023-11-15T20-43-25Z

**Comment by sathishkumar-p** [comment] 2024-01-09 03:58
yeah let me try with latest version of minio. Also should i update operator version ?

**Comment by harshavardhana** [comment] 2024-01-09 04:02
> yeah let me try with latest version of minio. Also should i update operator version ?

Upgrading operator is important as well.

**Comment by sathishkumar-p** [comment] 2024-01-10 04:35
Sure i will upgrade the operator, but is that issue ?

**Comment by sathishkumar-p** [comment] 2024-01-16 08:09
Hello @allanrogerr ,
Here the logs of test env , as you described.
[pool-0.log](https://github.com/minio/operator/files/13947034/pool-0.log)
[pool-1.log](https://github.com/minio/operator/files/13947046/pool-1.log)
[pool-2.log](https://github.com/minio/operator/files/13947062/pool-2.log)
[pool-3.log](https://github.com/minio/operator/files/13947080/pool-3.log)
[pool-4.log](https://github.com/minio/operator/files/13947086/pool-4.log)

**Comment by sathishkumar-p** [comment] 2024-01-24 07:14
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"minio.min.io/v2","kind":"Tenant","metadata":{"annotations":{"prometheus.io/path":"/minio/v2/metrics/cluster","prometheus.io/port":"9000","prometheus.io/scheme":"http","prometheus.io/scrape":"true"},"labels":{"app":"minio","argocd.argoproj.io/instance":"minio-tenant"},"name":"minio","namespace":"minio"},"spec":{"configuration":{"name":"myminio-env-configuration"},"env":[{"name":"MINIO_PROMETHEUS_URL","value":"http://i3-monitoring-prometheus-server.i3-monitoring.svc.cluster.local"},{"name":"MINIO_PROMETHEUS_AUTH_TYPE","value":"public"}],"features":{"bucketDNS":false},"image":"registry-emea.app.corpintra.net/dnaplatform/minio/minio:RELEASE.2023-08-31T15-31-16Z","imagePullPolicy":"IfNotPresent","logging":{"anonymous":false,"json":true,"quiet":true},"mountPath":"/export","podManagementPolicy":"Parallel","pools":[{"containerSecurityContext":{"runAsGroup":1000,"runAsNonRoot":true,"runAsUser":1000},"name":"pool-0","resources":{"limits":{"cpu":"2000m","memory":"1000Mi"},"requests":{"cpu":"1500m","memory":"700Mi"}},"securityContext":{"fsGroup":1000,"runAsGroup":1000,"runAsNonRoot":true,"runAsUser":1000},"servers":4,"volumeClaimTemplate":{"metadata":{"name":"data"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"cinder-retain"}},"volumesPerServer":4},{"containerSecurityContext":{"runAsGroup":1000,"runAsNonRoot":true,"runAsUser":1000},"name":"pool-2","resources":{"limits":{"cpu":"2000m","memory":"1000Mi"},"requests":{"cpu":"1500m","memory":"700Mi"}},"securityContext":{"fsGroup":1000,"runAsGroup":1000,"runAsNonRoot":true,"runAsUser":1000},"servers":4,"volumeClaimTemplate":{"metadata":{"name":"data"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"cinder-retain"}},"volumesPerServer":4},{"containerSecurityContext":{"runAsGroup":1000,"runAsNonRoot":true,"runAsUser":1000},"name":"pool-1","resources":{"limits":{"cpu":"2000m","memory":"1000Mi"},"requests":{"cpu":"1500m","memory":"700Mi"}},"securityContext":{"fsGroup":1000,"runAsGroup":1000,"runAsNonRoot":true,"runAsUser":1000},"servers":4,"volumeClaimTemplate":{"metadata":{"name":"data"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"cinder-retain"}},"volumesPerServer":4},{"containerSecurityContext":{"runAsGroup":1000,"runAsNonRoot":true,"runAsUser":1000},"name":"pool-3","resources":{"limits":{"cpu":"2000m","memory":"1000Mi"},"requests":{"cpu":"1500m","memory":"700Mi"}},"securityContext":{"fsGroup":1000,"runAsGroup":1000,"runAsNonRoot":true,"runAsUser":1000},"servers":4,"volumeClaimTemplate":{"metadata":{"name":"data"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"cinder-retain"}},"volumesPerServer":4},{"containerSecurityContext":{"runAsGroup":1000,"runAsNonRoot":true,"runAsUser":1000},"name":"pool-4","resources":{"limits":{"cpu":"2000m","memory":"1000Mi"},"requests":{"cpu":"1500m","memory":"700Mi"}},"securityContext":{"fsGroup":1000,"runAsGroup":1000,"runAsNonRoot":true,"runAsUser":1000},"servers":4,"volumeClaimTemplate":{"metadata":{"name":"data"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"2Gi"}},"storageClassName":"cinder-retain"}},"volumesPerServer":4}],"prometheusOperator":false,"requestAutoCert":false,"subPath":"/data"}}
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: '9000'
    prometheus.io/scheme: http
    prometheus.io/scrape: 'true'
  creationTimestamp: '2024-01-05T08:15:45Z'
  generation: 1
  labels:
    app: minio
    argocd.argoproj.io/instance: minio-tenant
  managedFields:
    - apiVersion: minio.min.io/v2
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:prometheus.io/path: {}
            f:prometheus.io/port: {}
            f:prometheus.io/scheme: {}
            f:prometheus.io/scrape: {}
          f:labels:
            .: {}
            f:app: {}
            f:argocd.argoproj.io/instance: {}
        f:spec:
          .: {}
          f:configuration: {}
          f:env: {}
          f:features:
            .: {}
            f:bucketDNS: {}
          f:image: {}
          f:imagePullPolicy: {}
          f:logging:
            .: {}
            f:anonymous: {}
            f:json: {}
            f:quiet: {}
          f:mountPath: {}
          f:podManagementPolicy: {}
          f:pools: {}
          f:prometheusOperator: {}
          f:requestAutoCert: {}
          f:subPath: {}
      manager: argocd-application-controller
      operation: Update
      time: '2024-01-05T08:15:45Z'
    - apiVersion: minio.min.io/v2
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:min.io/revision: {}
          f:labels:
            f:v1.min.io/console: {}
            f:v1.min.io/pool: {}
            f:v1.min.io/tenant: {}
        f:scheduler:
          .: {}
          f:name: {}
        f:status:
          .: {}
          f:availableReplicas: {}
          f:certificates:
            .: {}
            f:autoCertEnabled: {}
            f:customCertificates: {}
          f:currentState: {}
          f:drivesOnline: {}
          f:healthStatus: {}
          f:pools: {}
          f:revision: {}
          f:syncVersion: {}
          f:usage:
            .: {}
            f:rawCapacity: {}
            f:rawUsage: {}
          f:writeQuorum: {}
      manager: minio-operator
      operation: Update
      subresource: status
      time: '2024-01-24T07:13:28Z'
  name: minio
  namespace: minio
  resourceVersion: '2079958833'
  uid: f3991c8c-7e8e-4444-b4ca-ddcaad815b0f
  selfLink: /apis/minio.min.io/v2/namespaces/minio/tenants/minio
status:
  availableReplicas: 20
  certificates:
    autoCertEnabled: false
    customCertificates: {}
  currentState: Initialized
  drivesOnline: 80
  healthStatus: green
  pools:
    - legacySecurityContext: false
      ssName: minio-pool-0
      state: PoolInitialized
    - legacySecurityContext: false
      ssName: minio-pool-2
      state: PoolInitialized
    - legacySecurityContext: false
      ssName: minio-pool-1
      state: PoolInitialized
    - legacySecurityContext: false
      ssName: minio-pool-3
      state: PoolInitialized
    - legacySecurityContext: false
      ssName: minio-pool-4
      state: PoolInitialized
  revision: 0
  syncVersion: ''
  usage:
    rawCapacity: 103079215104
    rawUsage: 77359329280
  writeQuorum: 12
spec:
  configuration:
    name: myminio-env-configuration
  env:
    - name: MINIO_PROMETHEUS_URL
      value: http://i3-monitoring-prometheus-server.i3-monitoring.svc.cluster.local
    - name: MINIO_PROMETHEUS_AUTH_TYPE
      value: public
  features:
    bucketDNS: false
  image: >-
    registry-emea.app.corpintra.net/dnaplatform/minio/minio:RELEASE.2023-08-31T15-31-16Z
  imagePullPolicy: IfNotPresent
  logging:
    anonymous: false
    json: true
    quiet: true
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
    - containerSecurityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      name: pool-0
      resources:
        limits:
          cpu: 2000m
          memory: 1000Mi
        requests:
          cpu: 1500m
          memory: 700Mi
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      servers: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: cinder-retain
      volumesPerServer: 4
    - containerSecurityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      name: pool-2
      resources:
        limits:
          cpu: 2000m
          memory: 1000Mi
        requests:
          cpu: 1500m
          memory: 700Mi
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      servers: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: cinder-retain
      volumesPerServer: 4
    - containerSecurityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      name: pool-1
      resources:
        limits:
          cpu: 2000m
          memory: 1000Mi
        requests:
          cpu: 1500m
          memory: 700Mi
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      servers: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: cinder-retain
      volumesPerServer: 4
    - containerSecurityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      name: pool-3
      resources:
        limits:
          cpu: 2000m
          memory: 1000Mi
        requests:
          cpu: 1500m
          memory: 700Mi
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      servers: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: cinder-retain
      volumesPerServer: 4
    - containerSecurityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      name: pool-4
      resources:
        limits:
          cpu: 2000m
          memory: 1000Mi
        requests:
          cpu: 1500m
          memory: 700Mi
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      servers: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
          storageClassName: cinder-retain
      volumesPerServer: 4
  prometheusOperator: false
  requestAutoCert: false
  subPath: /data

**Comment by sathishkumar-p** [comment] 2024-01-24 07:17
tenant spec: 
[tenant.txt](https://github.com/minio/operator/files/14034766/tenant.txt)

Do you think will this prb with PVC ?

**Comment by allanrogerr** [comment] 2024-02-17 17:52
@sathishkumar-p Sorry for the late response. The spec provides give no clues as to what your issue is. When I mention exact steps, I need to know what your working with. 

Otherwise I can make a simple walkthru showing how to achieve what you're attempting to do using my own methods - probably a smaller setup.

**Comment by harshavardhana** [comment] 2024-02-17 18:49
This should be fixed in the latest MinIO release. 

Please upgrade the image a type of a similar issue was addressed with MinIO server.

Thanks closing this for now.

**Closed by harshavardhana** 2024-02-17 18:49 UTC
Labels: question, community, triage
