### ISSUE TITLE
host 127.0.0.1:9000: rename /usr/bin/minio /usr/bin/.minio.old: operation not permitted

### ISSUE THREAD

**Issue by pschichtel** [minio/operator#2319] opened 2024-09-15 12:32 UTC
The chain of operator upgrade issues continues after #2305. This time:

```
main-controller.go:1570] error syncing 'minio/tenant': host 127.0.0.1:9000: rename /usr/bin/minio /usr/bin/.minio.old: operation not permitted
```

When updating the image in the tenant resource.

The upgrade is from `RELEASE.2024-08-29T01-40-52Z` to `RELEASE.2024-09-13T20-26-02Z`.

The rest of the setup is identical to #2305.

**Comment by pschichtel** [comment] 2024-09-15 12:35
Manually editing the STS "works around" the issue as last time.

**Comment by pschichtel** [comment] 2024-09-15 12:37
I'm wondering: is my setup somehow special or is the upgrade process via operator just not being used much?

**Comment by harshavardhana** [comment] 2024-09-15 16:50
It looks like your set-up doesn't allow renames() there is nothing much we can do here. It looks like the image is treated as immutable in your environment.

**Comment by harshavardhana** [comment] 2024-09-15 16:53
We have tests already for this that work in regular k8s deployment. We don't ever come across any other non k8s deployments so we never really test it.

If you can reproduce on k8s or openshift we can take a look at how we can handle these cases.

Any other vendor here is out of scope for us.

**Comment by harshavardhana** [comment] 2024-09-15 20:23
Interesting, let me see if I can make that path fully writable for all users.

**Closed** 2024-09-15 23:10 UTC
Labels: community, triage

**Comment by pschichtel** [comment] 2024-09-16 09:40
@harshavardhana did you also republish the latest images?

**Comment by harshavardhana** [comment] 2024-09-16 14:47
> @harshavardhana did you also republish the latest images?

I did @pschichtel

**Comment by pschichtel** [comment] 2024-09-16 18:50
I have this image in production now, let's see how the next upgrade goes :)
