### ISSUE TITLE
stuck at Provisioning initial users

### ISSUE THREAD

**Issue by 13567436138** [minio/operator#1513] opened 2023-03-16 08:17 UTC
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Current Behavior

```
W0316 08:10:16.995176       1 warnings.go:70] unknown field "spec.pools[0].volumeClaimTemplate.metadata.creationTimestamp"
E0316 08:10:51.057497       1 main-controller.go:618] error syncing 'minio-tenant-2/minio-tenant-2': context deadline exceeded
I0316 08:10:51.058737       1 event.go:285] Event(v1.ObjectReference{Kind:"Tenant", Namespace:"minio-tenant-2", Name:"minio-tenant-2", UID:"d6547ab9-a800-49bc-831b-cfdb6d3379c1", APIVersion:"minio.min.io/v2", ResourceVersion:"623606", FieldPath:""}): type: 'Warning' reason: 'UsersCreatedFailed' Users creation failed: context deadline exceeded
I0316 08:10:56.855417       1 monitoring.go:172] 'minio-tenant-2/minio-tenant-2' Failed to get storage info: Server not initialized, please try again.
W0316 08:10:58.949423       1 warnings.go:70] unknown field "spec.pools[0].volumeClaimTemplate.metadata.creationTimestamp"
E0316 08:11:51.195544       1 main-controller.go:618] error syncing 'minio-tenant-2/minio-tenant-2': context deadline exceeded
I0316 08:11:51.195943       1 event.go:285] Event(v1.ObjectReference{Kind:"Tenant", Namespace:"minio-tenant-2", Name:"minio-tenant-2", UID:"d6547ab9-a800-49bc-831b-cfdb6d3379c1", APIVersion:"minio.min.io/v2", ResourceVersion:"623606", FieldPath:""}): type: 'Warning' reason: 'UsersCreatedFailed' Users creation failed: context deadline exceeded
I0316 08:12:16.976914       1 monitoring.go:172] 'minio-tenant-2/minio-tenant-2' Failed to get storage info: Server not initialized, please try again.
I0316 08:12:16.997831       1 monitoring.go:172] 'minio-tenant-2/minio-tenant-2' Failed to get storage info: context deadline exceeded
E0316 08:12:51.344879       1 main-controller.go:618] error syncing 'minio-tenant-2/minio-tenant-2': context deadline exceeded
I0316 08:12:51.346279       1 event.go:285] Event(v1.ObjectReference{Kind:"Tenant", Namespace:"minio-tenant-2", Name:"minio-tenant-2", UID:"d6547ab9-a800-49bc-831b-cfdb6d3379c1", APIVersion:"minio.min.io/v2", ResourceVersion:"623606", FieldPath:""}): type: 'Warning' reason: 'UsersCreatedFailed' Users creation failed: context deadline exceeded
W0316 08:13:16.697476       1 warnings.go:70] unknown field "spec.pools[0].volumeClaimTemplate.metadata.creationTimestamp"
E0316 08:13:51.446231       1 main-controller.go:618] error syncing 'minio-tenant-2/minio-tenant-2': context deadline exceeded
I0316 08:13:51.446694       1 event.go:285] Event(v1.ObjectReference{Kind:"Tenant", Namespace:"minio-tenant-2", Name:"minio-tenant-2", UID:"d6547ab9-a800-49bc-831b-cfdb6d3379c1", APIVersion:"minio.min.io/v2", ResourceVersion:"623606", FieldPath:""}): type: 'Warning' reason: 'UsersCreatedFailed' Users creation failed: context deadline exceeded

```

![image](https://user-images.githubusercontent.com/31508490/225555408-652f7025-9ad5-4b27-8e92-dde3c1ee9cf7.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
root@cluster3-159:~# mc --version
mc version RELEASE.2023-02-28T00-12-59Z (commit-id=5fbe8c26bab5592f0bc521db00665f8670a0fb31)
Runtime: go1.19.6 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

* Server setup and configuration:
* Operating System and version (`uname -a`):
root@cluster3-159:~# uname -a
Linux cluster3-159 5.19.0-31-generic minio/minio#32-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 20 15:20:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dvaldivia** [comment] 2023-03-16 14:59
Users are not getting provisioned because MinIO is not coming online, what is the output of "kubectl -n NAMESPACE get pods" and please share the logs of any pod restarting or if pending its description

**Comment by 13567436138** [comment] 2023-03-17 04:15
```
root@cluster3-159:~# kubectl get pod -n minio-tenant-2 
NAME                      READY   STATUS    RESTARTS      AGE
minio-tenant-2-pool-0-0   1/1     Running   0             20h
minio-tenant-2-pool-0-1   1/1     Running   1 (23h ago)   7d2h
minio-tenant-2-pool-0-2   1/1     Running   1 (23h ago)   7d2h
minio-tenant-2-pool-0-3   1/1     Running   0             20h

```
```
Waiting for all other servers to be online to format the drives (elapses 20h23m4s)

Waiting for all other servers to be online to format the drives (elapses 20h23m4s)

Waiting for all other servers to be online to format the drives (elapses 20h23m4s)

Waiting for all other servers to be online to format the drives (elapses 20h23m4s)

Waiting for all other servers to be online to format the drives (elapses 20h23m5s)

Waiting for all other servers to be online to format the drives (elapses 20h23m5s)

Waiting for all other servers to be online to format the drives (elapses 20h23m5s)

```

**Comment by 13567436138** [comment] 2023-03-17 10:17
I0317 10:17:05.646602       1 event.go:285] Event(v1.ObjectReference{Kind:"Tenant", Namespace:"minio-tenant-1", Name:"minio-tenant-1", UID:"ebbcc4a2-7a68-4602-87ff-1ca87fc6b825", APIVersion:"minio.min.io/v2", ResourceVersion:"835575", FieldPath:""}): type: 'Warning' reason: 'UsersCreatedFailed' Users creation failed: context deadline exceeded

**Comment by 13567436138** [comment] 2023-03-17 13:14
7 13:13:35.954786       1 warnings.go:70] unknown field "spec.pools[0].volumeClaimTemplate.metadata.creationTimestamp"
W0317 13:13:35.966376       1 warnings.go:70] unknown field "spec.pools[0].volumeClaimTemplate.metadata.creationTimestamp"
W0317 13:13:36.034349       1 warnings.go:70] unknown field "spec.pools[0].volumeClaimTemplate.metadata.creationTimestamp"
W0317 13:13:36.054066       1 warnings.go:70] unknown field "spec.pools[0].volumeClaimTemplate.metadata.creationTimestamp"
W0317 13:13:36.159715       1 warnings.go:70] unknown field "spec.pools[0].volumeClaimTemplate.metadata.creationTimestamp"
W0317 13:13:36.181129       1 warnings.go:70] unknown field "spec.pools[0].volumeClaimTemplate.metadata.creationTimestamp"

**Comment by dvaldivia** [comment] 2023-03-17 17:34
are tehre any other logs other than these warnings? @13567436138 

Another reason could be that the operator cannot talk to MinIO due to TLS, does your tenant has TLS enabled? 

what distribution of kubernetes are you using?

**Comment by bRuSh12** [comment] 2023-03-17 20:33
I am also having this same exact issue creating a new tenant. I am using OpenShift 4.10.53 which is kubernetes v1.23.12+8a6bfe4.

 

Minio release info:

 

image: minio/minio:RELEASE.2023-01-12T02-06-16Z

 

I am provisioning a tenant with 3 servers, 2 volumes each.

**Comment by bRuSh12** [comment] 2023-03-17 20:47
[report.tgz](https://github.com/minio/operator/files/11006135/report.tgz)

**Comment by 13567436138** [comment] 2023-03-17 22:35
I am ok，now

**Comment by bRuSh12** [comment] 2023-03-20 12:38
Was there any change to resolve the issue? My tenant is still in the "Provisioning initial users" state

**Comment by jeremyssc** [comment] 2023-09-06 15:00
> I ran into this issue using Openshift 4.10.47. I was able to resolve it by implementing a Network Policy that allowed the 'openshift-operators' namespace to communicate with the minio tenant pod.
> 
> kind: NetworkPolicy apiVersion: networking.k8s.io/v1 metadata: name: example namespace: {Tenant Namespace} spec: podSelector: matchLabels: app: minio ingress: - from: - namespaceSelector: matchLabels: kubernetes.io/metadata.name: openshift-operators - podSelector: matchLabels: app.kubernetes.io/instance: minio-operator policyTypes: - Ingress

Thank you, I was able to solve the issue after tweaking it to match all pods in the namespace since the pods minio pods didn't have the app label:
`kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
 name: example
 namespace: Tenant Namespace}
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-operators
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: minio-operator
  policyTypes:
    - Ingress`

**Comment by cesnietor** [comment] 2023-09-11 16:55
closing since it seems solved, please open a new one if this is not the case with more reproduceable steps.

**Closed by cesnietor** 2023-09-11 16:55 UTC
Labels: community, triage
