### ISSUE TITLE
--console-image, --default-minio-image options doesn't work

### ISSUE THREAD

**Issue by next0262** [minio/operator#1453] opened 2023-02-17 06:05 UTC
**I tried to initialize minio-operator with  --console-image, --default-minio-image options like this** : 
$ kubectl minio init  --console-image minio/console:v0.20.2 --console-image minio/console:v0.20.2 --default-minio-image minio/minio:RELEASE.2022-09-22T18-57-27Z --image minio/operator:v4.5.4

--console-image
Optional
The default [MinIO Console](https://github.com/minio/console) image to use when creating a new MinIO tenant. Defaults to minio/console:v0.17.3.

--default-minio-image
Optional
The default [minio](https://github.com/minio/minio) image to use when creating a new MinIO tenant. Defaults to minio/minio:RELEASE.2022-05-26T05-48-41Z.

**but, the operator didn't use these implicit images of the options for creating tenants.**, --console-image minio/console:v0.20.2 --default-minio-image minio/minio:RELEASE.2022-09-22T18-57-27Z, 

**What should i do? As i checked the code of the operator, it looks like not using these options. Am i right?**

**And i want to separate minio console from minio server for our minio operation environment. To do this, is there any guide i can refer to? or this separation is not recommended??**

**Comment by cesnietor** [comment] 2023-10-02 16:49
we'll test and see if we can reproduce this issue with latest code.

**Comment by cniackz** [comment] 2023-10-10 15:54
There is no `--default-console-image` flag in our plugin

**Comment by cniackz** [comment] 2023-10-10 15:54
Supported flags in version 5.0.9 are:
```
Cesars-MacBook-Pro:~ cniackz$ k minio version
v5.0.9
Cesars-MacBook-Pro:~ cniackz$ kubectl minio init --help

 'init' command creates MinIO Operator deployment along with all the dependencies.

Usage:
  minio init [flags]

Examples:
  kubectl minio init

Flags:
  -d, --cluster-domain string         cluster domain of the Kubernetes cluster (default "cluster.local")
      --console-image string          console image
      --console-tls                   enable tls for Operator console
      --default-kes-image string      default tenant KES image
      --default-minio-image string    default tenant MinIO image
  -h, --help                          help for init
  -i, --image string                  operator image (default "minio/operator:v5.0.9")
      --image-pull-secret string      image pull secret to be used for pulling MinIO Operator
  -n, --namespace string              namespace scope for this request (default "minio-operator")
      --namespace-to-watch string     namespace where operator looks for MinIO tenants, leave empty for all namespaces
  -o, --output                        dry run this command and generate requisite yaml
      --prometheus-name string        name of the prometheus managed by prometheus-operator
      --prometheus-namespace string   namespace of the prometheus managed by prometheus-operator
      --sts                           enable Operator sts (v1alpha1)

Global Flags:
      --kubeconfig string   Custom kubeconfig path
```

**Comment by cniackz** [comment] 2023-10-10 16:30
This `--console-image` refers to the console image in Operator.
We split UI in two, React project is now located in Operator for Operator and in Console for Console.
So in other words, `--console-image` is for the Operator's Console only.
If you intended to change the image in the Tenant, then, console image goes with MinIO image. So for that all you need to change is minio image not the operator console image. So here the explanation:


* Tenant Console: `--default-minio-image` <---- Tenant Front End
* MinIO Image: `--default-minio-image` <---- Tenant Back End
* Operator console: `--console-image` <---- Operator Front End
* Operator BackEnd image: `--image` <----- Operator Backend

Our official doc is wrong, I will update the docs and close this issue once we merge those changes in docs repo.

**Comment by cniackz** [comment] 2023-10-10 16:31
The other issue is located at https://min.io/docs/minio/kubernetes/upstream/reference/kubectl-minio-plugin/kubectl-minio-init.html#kubectl.minio.init.-console-image we are pointing to wrong repo for Console. We should point to operator here!.

**Comment by cniackz** [comment] 2023-10-10 16:38
Ok, https://github.com/minio/docs/pull/1031 has been merged, let's go into the next problem.

**Closed** 2023-10-10 17:02 UTC
Labels: community, triage

**Comment by cniackz** [comment] 2023-10-10 17:15
https://github.com/minio/docs/pull/1032 got merged, explanation can be found here: https://github.com/minio/wiki/wiki/How-to-set-our-different-images-via-Operator-plugin

**Comment by cniackz** [comment] 2023-10-10 17:15
@next0262 thank you for openning the issue; please read thru and test again in our latest Operator/Tenant versions. And if you encounter any other issue, let us know!. 👍
