### ISSUE TITLE
`.tenant.configSecret` is unusable due to default value in `.secrets`

### ISSUE THREAD

**Issue by v1nsai** [minio/operator#2283] opened 2024-08-21 13:01 UTC
## Expected Behavior
I should be able to configure `.tenant.configSecret` in the minio tenant helm chart without errors about `.secrets` even though I have not entered any config for `.secrets`.

## Current Behavior
When entering values in `.tenant.configSecret`, an error is encountered because `.secrets` has a default value, making it impossible to use due to [the error checking here](https://github.com/minio/operator/blob/97d95fa53b6c3d8f45a313cad9c71735fed315e7/helm/tenant/templates/tenant-configuration.yaml#L5).  I tried adding `.secrets: {}` to values but that didn't work.

## Possible Solution
Moving the default values from the deprecated `.secrets` into `.tenant.configSecret` seems like it would do the trick.

## Steps to Reproduce (for bugs)
1.  Enter values for `.tenant.configSecret`, do not use `.secrets` at all
2.  Get error about `.secrets` and `.tenant.configSecret` being mutually exclusive

## Context
Not able to preconfigure an access key or a secret key in the tenant helm chart.

## Regression
Seems like this is a regression due to handling for imminent deprecation of `.secrets`.  Operator and tenant version 6.0.2

## Your Environment
* Version used (`minio-operator`): 
      minio-tenant
* Environment name and version (e.g. kubernetes v1.17.2):
      k3s version v1.30.3+k3s1
* Server type and version:
      Client Version: v1.30.1
      Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
      Server Version: v1.30.3+k3s1
* Operating System and version (`uname -a`):
      Ubuntu 24.04
* Link to your deployment file:
```yaml
tenant:
  name: homelab-minio
  configSecret:
    name: user-config
    existingSecret: true
```

**Comment by ramondeklein** [comment] 2024-08-22 10:08
Duplicate of #2255.

**Closed by ramondeklein** 2024-08-22 10:08 UTC
Labels: community, triage
