### ISSUE TITLE
port forwarding to operator console times out

### ISSUE THREAD

**Issue by De1taE1even** [minio/operator#1451] opened 2023-02-16 19:35 UTC
I'm using the default configuration, and was able to reproduce this issue both on a local vsphere-backed rancher cluster, and one of our AKS clusters.  I am using the newest stable version as of this date, which is v4.5.8.

```
helm install --namespace minio-operator --create-namespace minio-operator minio/operator
(installs successfully, both operator and console come up fine)

kubectl -n minio-operator  get secret console-sa-secret -o jsonpath="{.data.token}" | base64 --decode
(jwt returns successfully)

kubectl --namespace minio-operator port-forward svc/console 9090:9090
(port forward works initially, and the ui can be reached, but immediately I see timeouts from the port-forward output)
  logs:
  E0216 12:21:49.460583   61197 portforward.go:378] error copying from remote stream to local connection: readfrom tcp6 [::1]:9090->[::1]:52421: write tcp6 [::1]:9090->[::1]:52421: write: broken pipe
  E0216 12:22:18.880764   61197 portforward.go:346] error creating error stream for port 9090 -> 9090: Timeout occurred
  E0216 12:22:19.363451   61197 portforward.go:346] error creating error stream for port 9090 -> 9090: Timeout occurred
  Handling connection for 9090
  E0216 12:22:49.370872   61197 portforward.go:346] error creating error stream for port 9090 -> 9090: Timeout occurred
  Handling connection for 9090
  E0216 12:23:19.378171   61197 portforward.go:346] error creating error stream for port 9090 -> 9090: Timeout occurred
  Handling connection for 9090
  E0216 12:23:49.385006   61197 portforward.go:346] error creating error stream for port 9090 -> 9090: Timeout occurred
```
I port forward to many other services just fine.  When I attempt to input the jwt into the login page, the page just sits there, and the request times out.  There are no logs from the operator or console pods related to the login attempt.  Seems like the request is never getting to the svc.

I was previously using version 4.3.7 of the operator, and this issue does not exist.

**Comment by dnskr** [comment] 2023-02-16 20:50
The issue is related to MinIO Console, see https://github.com/minio/console/issues/2539

**Comment by harshavardhana** [comment] 2023-02-17 02:26
Closing as duplicate of minio/console#2539

**Closed by harshavardhana** 2023-02-17 02:26 UTC
