### ISSUE TITLE
Creating a minio Tenant using the given commands from the README fails to start up the console in GKE

### ISSUE THREAD

**Issue by L1st3r** [minio/operator#398] opened 2020-12-21 20:40 UTC
In GKE after correctly setting up the MinIO operator, attempting to create a basic tenant fails to get the console to start up. It looks like it has an incorrect argument, and changing the arguments to what I have below does bring it up. 

## Current Behavior
This is what is in the generated yaml:
        - --certs-dir=/tmp/certs

And the error we get is:
"Incorrect Usage: flag provided but not defined: -certs-dir"

## Possible Solution
Using these arguments will allow the pods to start properly
        - --tls-certificate=/tmp/certs/public.crt
        - --tls-key=/tmp/certs/private.key

## Steps to Reproduce (for bugs)
1. Follow README.md instructions to init and setup minio operator
2. run: kubectl minio tenant create --name tenant1 --servers 4 --volumes 16 --capacity 1Ti
3. Watch the console not get healthy and the above error is in the logs
4.

## Context
This makes the operator not function without human interaction to get the system up and healthy

## Regression
No idea

## Your Environment
* Version used (`minio-operator`): 3.0.29
* Environment name and version (e.g. kubernetes v1.17.2): Kubernetes Client: 1.19.1   Kubernetes Server: 1.17.13
* Server type and version: GKE
* Operating System and version (`uname -a`): GKE
* Link to your deployment file: No link, just using the operator

**Comment by Alevsk** [comment] 2020-12-22 16:42
@L1st3r the docs are getting updated, in the meantime please update your console `deployment` to use `minio/console:v0.4.6` image, `--certs-dir` its a flag added on recent versions of Console

**Comment by johny-mnemonic** [comment] 2020-12-23 15:23
@Alevsk I happen to have the same issue. Would you please advice how to control which minio/console version the operator deploys?

**Comment by Alevsk** [comment] 2020-12-23 16:04
> @Alevsk I happen to have the same issue. Would you please advice how to control which minio/console version the operator deploys?

Please take a look at the example deployment files, ie: https://github.com/minio/operator/blob/master/examples/tenant-with-autocert-encryption-disabled.yaml, you can deploy your MinIO tenants using `kubectl apply -f file.yaml` and if you wish to customize the console image you can define a new value under:

```
  console:
    image: minio/console:v0.4.6
 ```

**Comment by anapsix** [comment] 2020-12-29 12:02
imho, the problem is not as much with the docs, as with `minio-operator` generating manifest with console's image version which is incompatible with `--certs-dir` cli option

**Comment by JLMonk** [comment] 2021-01-19 15:06
Did this get resolved? My operator is overwriting any changes I make to the console deployment.

**Comment by philippeboyd** [comment] 2021-01-28 16:34
Same problem as @JLMonk Operator resets everything... Why is the operator so behind in its console release? Latest console is at 0.5.2

**Comment by Alevsk** [comment] 2021-01-28 17:14
@philippeboyd we are very close to release the new version of operator which includes the fix for this issue, we just need a couple more man hrs for testing the v1 to v2 conversion https://github.com/minio/operator/pull/423#pullrequestreview-577861164

**Comment by akantak** [comment] 2021-02-24 14:16
@Alevsk any ETA for the new release date?

**Comment by harshavardhana** [comment] 2021-02-24 23:00
v4.0.0 released closing

**Closed by harshavardhana** 2021-02-24 23:00 UTC
