### ISSUE TITLE
Ingress Service for minio browser - minio svc port 443 is redirecting to 9443 

### ISSUE THREAD

**Issue by reddymh** [minio/operator#810] opened 2021-09-04 17:56 UTC
Created ingress service for minio service(port 443) & minio console service( 9443 ) but when I try to access ingress service for minio browser, its redirecting to from https://<HOSTNAME>:443 to https://<HOSTNAME:9443.

But works fine with minio client (mc).

One more issue is MINIO_SERVER_URL is hardcoded and not able to override with ingress url and always taking local service url.

Minio Operator Version: **4.2.2**

## Expected Behavior
Ingress service should work for minio browser pointing to minio svc with 443 port

## Current Behavior
Ingress service for minio svc with 443 port is redirecting to 9443 port

## Possible Solution
Should override env variable value for MINIO_SERVER_URL and MinIO Browser should work fine with UI.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio-operator`): v4.2.2
* Environment name and version (e.g. kubernetes v1.17.2): v1.19.7
* Server type and version: 
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by reddymh** [comment] 2021-09-04 18:28
And even tried accessing via NodePort by exposing the pods and try to access https://<HOSTNAME>:30238 node port which is redirecting to https://<HOSTNAME>:9443 port.

test-svc             NodePort    10.63.68.71    <none>        9000:30238/TCP,9443:30252/TCP   4s

**Comment by harshavardhana** [comment] 2021-09-04 21:30
Closing as duplicate of #790

**Closed by harshavardhana** 2021-09-04 21:30 UTC

**Comment by reddymh** [comment] 2021-09-06 06:27
Re-opening the issue - Ingress Service for minio browser - minio svc port 443 is redirecting to 9443

There is an issue when the minio svc with port 443. service is exposed via ingress is always redirecting to 9443.

Ingress yaml:

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-passthrough: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  labels:
    argocd.argoproj.io/instance: minio-test
  name: minio-test-ingress
  namespace: mn-minio-test
spec:
  rules:
  - host: minio-test.minio.com
    http:
      paths:
      - backend:
          serviceName: minio
          servicePort: 443
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - minio-test.minio.com

**Comment by harshavardhana** [comment] 2021-09-06 06:30
> @harshavardhana Re-opening the issue - Ingress Service for minio browser - minio svc port 443 is redirecting to 9443

Duplicate of #790
