### ISSUE TITLE
Deploying the operator without automatic certificates creation (helm)

### ISSUE THREAD

**Issue by jgato** [minio/operator#572] opened 2021-04-07 07:21 UTC
**Is your feature request related to a problem? Please describe.**
Whenever I deploy the operator (using helm/chart) I receive the error about "operator-tls" not found. An issue solved in other threads modifying the cluster configuration. In any case, I can access the Operator Console (only by http, because https is not working). But I am not sure if the tenant is really created, I cannot access MINIO console. 

**Describe the solution you'd like**
A way of deploy the Operator using my own certificates and not the automatic signing process. Also, the documentation is not clear about how you configure the Values.yaml for the Console (operator) and the Console for Minio. So, it is pretty difficult to know when to pass my own certificates, the credentials, etc (all these already exists in my cluster as secrets and I just want to

**Comment by harshavardhana** [comment] 2021-05-25 20:14
Duplicate of #601

**Closed by harshavardhana** 2021-05-25 20:14 UTC
