### ISSUE TITLE
minio-console:9090 redirects to 0.0.0.0:9443

### ISSUE THREAD

**Issue by mfbrj** [minio/operator#428] opened 2021-01-17 03:24 UTC
I installed a minio tenant using the following yml:
```
apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  creationTimestamp: null
  name: minio
  namespace: mynamespace
scheduler:
  name: ""
spec:
  certConfig: {}
  console:
    consoleSecret:
      name: minio-console-secret
    image: minio/console:v0.4.6
    metadata:
      creationTimestamp: null
      name: minio
    replicas: 2
    resources: {}
  credsSecret:
    name: minio-creds-secret
  image: minio/minio:RELEASE.2020-11-19T23-48-16Z
  imagePullSecret: {}
  mountPath: /export
  requestAutoCert: true
  serviceName: minio-internal-service
  zones:
  - resources: {}
    servers: 2
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2560Mi
        storageClassName: wffc
      status: {}
    volumesPerServer: 2
status:
  availableReplicas: 0
  currentState: ""

---
apiVersion: v1
data:
  accesskey: my-accesskey
  secretkey: my-secretkey
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-creds-secret
  namespace: mynamespace

---
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: myCONSOLE_ACCESS_KEY
  CONSOLE_HMAC_JWT_SECRET: myCONSOLE_HMAC_JWT_SECRET
  CONSOLE_PBKDF_PASSPHRASE: myCONSOLE_PBKDF_PASSPHRASE
  CONSOLE_PBKDF_SALT: myCONSOLE_PBKDF_SALT
  CONSOLE_SECRET_KEY: myCONSOLE_SECRET_KEY
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-console-secret
  namespace: mynamespace

```
When I try to access the gui minio-console:9090 it redirects to 0.0.0.0:9443

Someone reported the same problem at [stackoverflow](https://stackoverflow.com/questions/64827502/kubernetes-minio-tenant-ui-redirects-to-0-0-0-09443), unfortunally with no answers.

## Expected Behavior

Minio Console gui should be displayed.

## Current Behavior

Connection is redirected to 0.0.0.0:9443 returning a blank page.

## Steps to Reproduce (for bugs)

1. Install a minio tenant with the config above.
2. To avoid the complexity in configure a ingress, just try to access the minio-console:9090 from any pod in the same namespace using curl:
```
root@ubuntu-79969d4b85-s7mtj:/# curl minio-console:9090
<a href="https://0.0.0.0:9443/">Moved Permanently</a>.
```

## Your Environment

* Version used (`minio-operator`):
```
kubectl krew list
PLUGIN  VERSION
krew    v0.4.0
minio   v3.0.29

```
* Environment name and version (e.g. kubernetes v1.17.2):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

```
* Server type and version:
* Operating System and version (`uname -a`):
```
uname -a
Linux myhost 5.8.0-38-generic #43-Ubuntu SMP Tue Jan 12 12:42:13 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
* Link to your deployment file:

**Comment by owetterau** [comment] 2021-01-23 20:15
I am experiencing the same issue (redirect to 0.0.0.0:9443) with an Istio ingress pointing to the minio-console service.

My versions:
krew v0.4.0
minio operator v3.0.29
minio console v0.5.2 (updated manually)

**Comment by harshavardhana** [comment] 2021-01-24 00:10
Change the ports as necessary

```
FLAGS:
  --host value       HTTP server hostname (default: "0.0.0.0")
  --port value       HTTP Server port (default: 9090)
  --tls-host value   HTTPS server hostname (default: "0.0.0.0")
  --tls-port value   HTTPS server port (default: 9443)
```

Why is redirect a problem?

**Comment by owetterau** [comment] 2021-01-24 09:37
Console is installed via operator and therefore I think that these flags won't work.

Redirect is a problem: I am accessing the console on port 9090 via Istio ingress and HaProxy(external address https://minio.apps.kubernetes.<private domain>). But then the external address is being redirected to 0.0.0.0:9090 which obviously cannot be accessed from a browser outside of Kubernetes.

**Comment by harshavardhana** [comment] 2021-01-24 09:42
> Console is installed via operator and therefore I think that these flags won't work.

You can certainly add ENV and override them @owetterau in the `console:` section 

```
env: 
   CONSOLE_TLS_PORT: myport
   CONSOLE_TLS_HOSTNAME: myhostname
```

**Comment by owetterau** [comment] 2021-01-24 13:14
Unfortunately, when I change these settings, console tries to listen on the external address defined be these ENV variables which is impossible and leads to the console pods crashing...

The main issue seems to be that the console is redirecting requests going to the non-safe port (default 9090) to the secured port (9443) with its default IP address which it should not do, because the console's pod ENV variable MCS_SECURE_SSL_REDIRECT is set to "off" by the operator.

If the console would not redirect as requested by the ENV variable, everything would be ok...

**Comment by harshavardhana** [comment] 2021-01-24 18:41
> Unfortunately, when I change these settings, console tries to listen on the external address defined be these ENV variables which is impossible and leads to the console pods crashing...
> 
> The main issue seems to be that the console is redirecting requests going to the non-safe port (default 9090) to the secured port (9443) with its default IP address which it should not do, because the console's pod ENV variable MCS_SECURE_SSL_REDIRECT is set to "off" by the operator.
> 
> If the console did not redirect as requested by the ENV variable, everything would be ok...

That would be CONSOLE_SECURE_TLS_REDIRECT=off

**Comment by owetterau** [comment] 2021-01-24 19:42
I tried with CONSOLE_SECURE_TLS_REDIRECT=off, it does not work either.

**Comment by mfbrj** [comment] 2021-01-24 20:11
> Redirect is a problem: I am accessing the console on port 9090 via Istio ingress and HaProxy pointing to the Istio ingress (external address https://minio.apps.kubernetes.private.domain). But then the external address is being redirected to 0.0.0.0:9090 which obviously cannot be accessed from a browser outside of Kubernetes.

@owetterau clarified it well.
In my case, minio-console is in k8s cluster in DigitalOcean, with a Ingress working properly. I'm trying to access minio-console from my laptop outside the cluster and the redirect to 0.0.0.0 mess the browser navigation.

**Comment by harshavardhana** [comment] 2021-01-24 20:51
Closing as duplicate of https://github.com/minio/console/issues

**Closed by harshavardhana** 2021-01-24 20:51 UTC

**Comment by mfbrj** [comment] 2021-01-24 21:08
How can this issue be considered duplicated if it is older than [#573](https://github.com/minio/console/issues/573)?

**Comment by harshavardhana** [comment] 2021-01-24 21:10
> How can this issue be considered duplicated if it is older than [#573](https://github.com/minio/console/issues/573)?

The issue is related to console not related to operator @mfbrj

**Comment by mfbrj** [comment] 2021-01-24 21:12
Right. Thanks for the answer @harshavardhana

**Comment by EBallou** [comment] 2021-05-03 15:58
@harshavardhana is this supposed to be set in configmap, or console env directly?  minio           v4.0.9 release doesn't seem to make difference where set - still fails.

**Comment by harshavardhana** [comment] 2021-05-03 16:00
> @harshavardhana is this supposed to be set in configmap, or console env directly? minio v4.0.9 release doesn't seem to make difference where set - still fails.

This needs to be added in console ENV in your deployment - there is nothing failing here if you set up TLS it will redirect by default.

**Comment by PigNatovsky** [comment] 2021-07-28 07:10
> > @harshavardhana is this supposed to be set in configmap, or console env directly? minio v4.0.9 release doesn't seem to make difference where set - still fails.
> 
> This needs to be added in console ENV in your deployment - there is nothing failing here if you set up TLS it will redirect by default.

Could You please tell me, how can I add ENV to console deployment? Manifest is generated by operator (I'm using old 3.0.29, because our cluster is still in 1.18.x branch), but I don't see place in tenant definition to add additional configuration options.

**Comment by PigNatovsky** [comment] 2021-07-28 08:35
OK - I just addedd env to deploy and it works. So have a nice day :)
