### ISSUE TITLE
k8s operator expand not working

### ISSUE THREAD

**Issue by dotbalo** [minio/operator#340] opened 2020-10-15 07:12 UTC
I deployed a minio cluster on the k8s cluster using operator. 
**kubectl minio tenant create --name sct --servers 4 --volumes 4 --capacity 400Gi.**
At this time, the cluster is normal, and files can be upload and download.
Then I used expand to expand:
**kubectl minio tenant expand --name sct --servers 4 --volumes 4 --capacity 400Gi**
At this point, the PVC and Pod have been successfully created, but the Pod has printed **Waiting for the first server to format the disks**.

## Expected Behavior
The cluster can be used normally after expansion.

## Current Behavior
Pod keeps printing **Waiting for the first server to format the disks**.

## Steps to Reproduce (for bugs)
1. kubectl minio tenant create --name sct --servers 4 --volumes 4 --capacity 400Gi
2. kubectl minio tenant expand --name sct --servers 4 --volumes 4 --capacity 400Gi

## Context
I want to expand my cluster.

## Regression
No

## Your Environment

* Version used (`minio-operator`):  **minio/k8s-operator:v3.0.26**
* Environment name and version (e.g. kubernetes v1.17.2): **1.18.9**
* Server type and version:  **CentOS Linux release 7.6.1810 (Core)**
* Operating System and version (`uname -a`): **Linux k8s-master01 4.18.9-1.el7.elrepo.x86_64 #1 SMP Thu Sep 20 09:04:54 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux**
* Link to your deployment file: 
````
# kubectl get tenant sct -oyaml
apiVersion: minio.min.io/v1
kind: Tenant
metadata:
    manager: minio-operator
    operation: Update
  name: sct
  namespace: default
scheduler:
  name: ""
spec:
  certConfig: {}
  console:
    consoleSecret:
      name: sct-console-secret
    image: minio/console:v0.3.14
    imagePullPolicy: IfNotPresent
    metadata:
      name: sct
    replicas: 1
    resources: {}
  credsSecret:
    name: sct-creds-secret
  image: minio/minio:RELEASE.2020-09-26T03-44-56Z
  imagePullPolicy: IfNotPresent
  imagePullSecret: {}
  labels:
    app: minio
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 1
    timeoutSeconds: 1
  mountPath: /export
  requestAutoCert: false
  serviceName: sct-internal-service
  zones:
  - resources: {}
    servers: 4
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: local-storage
      status: {}
    volumesPerServer: 1
  - resources: {}
    servers: 4
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
      status: {}
    volumesPerServer: 1
status:
  availableReplicas: 8
  currentState: Initialized
````
````
[root@k8s-master01 ~]# kubectl get pvc
NAME                  STATUS   VOLUME                CAPACITY   ACCESS MODES   STORAGECLASS          AGE
0-sct-zone-0-0        Bound    sct-4                 100Gi      RWO            local-storage         167m
0-sct-zone-0-1        Bound    sct-1                 100Gi      RWO            local-storage         167m
0-sct-zone-0-2        Bound    sct-2                 100Gi      RWO            local-storage         167m
0-sct-zone-0-3        Bound    sct-7                 100Gi      RWO            local-storage         167m
0-sct-zone-1-0        Bound    sct-0                 100Gi      RWO            local-storage         164m
0-sct-zone-1-1        Bound    sct-5                 100Gi      RWO            local-storage         164m
0-sct-zone-1-2        Bound    sct-6                 100Gi      RWO            local-storage         164m
0-sct-zone-1-3        Bound    sct-3                 100Gi      RWO            local-storage         164m
````

PV is created in different directories of four servers:
````
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: 0-sct-zone-0-1
    namespace: default
  local:
    path: /data/sct
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-master03
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
````
logs:
````
[root@k8s-master01 ~]# kubectl logs -f sct-zone-1-3   --tail 10
Waiting for the first server to format the disks.
Waiting for the first server to format the disks.
Waiting for the first server to format the disks.
...


kubectl logs -f minio-operator-69f7c4897c-m5jmj   -n minio-operator --tail 10
I1015 07:11:18.000179       1 main-controller.go:761] Successfully synced 'minio/minio'
I1015 07:11:18.000638       1 main-controller.go:761] Successfully synced 'default/sct'
I1015 07:11:47.968037       1 main-controller.go:761] Successfully synced 'default/sct'
I1015 07:11:47.969326       1 main-controller.go:761] Successfully synced 'minio/minio'
I1015 07:11:47.989404       1 main-controller.go:761] Successfully synced 'default/sct'
I1015 07:11:47.990251       1 main-controller.go:761] Successfully synced 'minio/minio'
I1015 07:12:17.971096       1 main-controller.go:761] Successfully synced 'default/sct'
I1015 07:12:17.972924       1 main-controller.go:761] Successfully synced 'minio/minio'
I1015 07:12:17.996363       1 main-controller.go:761] Successfully synced 'default/sct'
I1015 07:12:17.996363       1 main-controller.go:761] Successfully synced 'minio/minio'

````

How can I check and deal with this problem?

**Comment by harshavardhana** [comment] 2020-10-15 07:14
> * Version used (`minio-operator`):  **minio/k8s-operator:v3.0.26**

you need to upgrade to latest release.

**Comment by dotbalo** [comment] 2020-10-15 07:26
@harshavardhana Thank you so much for your answer.
How do I upgrade the operator? I used **kubectl minio** and did not find the upgrade command. In addition, after upgrading the operator, do I need to upgrade the tenant version to latest?

**Comment by dotbalo** [comment] 2020-10-15 08:08
I uninstalled the operator, and then designated the image as minio/k8s-operator:latest. But expand still has the same error.
And deleting the operator will delete the minio cluster, which is very bad. But I did not find an upgrade command.

**Comment by anapsix** [comment] 2020-10-30 18:00
@harshavardhana, unfortunately krew is still showing `v3.0.26` as latest

- downloaded `v3.0.28` from [releases](https://github.com/minio/operator/releases)
- deleted operator
- deleted old PVCs (!important!, operator does not overwrite existing PVCs)
- init operator
- generated tenant manifefst
   ```
   ./kubectl-minio_3.0.28_darwin_amd64 \
      tenant create \
      --namespace minio-test \
      --name tenant1 \
      --servers 2 \
      --volumes 4 \
      --capacity 16Gi -o > minio_tenant.yaml
   ```
- edited manifest, adding `storageClassName: nfs-client`
- applied manifest
- checked pods and pvcs - all is good, storage class was set properly

**Comment by djfoley01** [comment] 2020-11-20 14:10
I'm experiencing the same issue with 3.0.28. Exact same issue except my environment is a little different, using kube 1.19.0 and RHEL 7.9.

**Comment by nitisht** [comment] 2020-11-21 05:30
We'll take a look and get back.

**Comment by nitisht** [comment] 2020-11-24 13:49
@djfoley01 I tried on my local setup and expansion seems to be working fine. Can you elaborate what did you try and what did not work?

**Comment by djfoley01** [comment] 2020-11-24 15:49
@nitisht I'll create a step by step and exactly what I'm seeing. Essentially I go to perform the expansions, and each new "node" just sits there stating:
"Waiting for the first server to format the disks.
Waiting for the first server to format the disks.
Waiting for the first server to format the disks."

**Comment by nitisht** [comment] 2020-11-24 15:52
> @nitisht I'll create a step by step and exactly what I'm seeing. Essentially I go to perform the expansions, and each new "node" just sits there stating:
> "Waiting for the first server to format the disks.
> Waiting for the first server to format the disks.
> Waiting for the first server to format the disks."

This may be due to improper PV etc, we'll need to look at your setup / steps

**Comment by djfoley01** [comment] 2020-11-24 16:17
It's kind of long, but you can see exactly what I did and what was created:

`$ oc minio tenant create --name minio-sandbox --servers 4 --volumes 4 --capacity 1Ti --namespace minio
$ oc get pvc
NAME                       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
0-minio-sandbox-zone-0-0   Bound    pvc-db00aef2-a48d-4f36-8335-4c6fe4abb157   256Gi      RWO            thin           3d19h
0-minio-sandbox-zone-0-1   Bound    pvc-25acf08f-b4c9-4027-a090-dfdbbd1599c3   256Gi      RWO            thin           3d19h
0-minio-sandbox-zone-0-2   Bound    pvc-39b87ac0-5766-401e-9006-553259e1b768   256Gi      RWO            thin           3d19h
0-minio-sandbox-zone-0-3   Bound    pvc-de68af50-6980-4a57-ad8b-8463cd6a5bff   256Gi      RWO            thin           3d19h
$ oc get pods
NAME                                     READY   STATUS    RESTARTS   AGE
minio-operator-5f7fd98c7d-xp9hd          1/1     Running   0          4d23h
minio-sandbox-console-6d67f645f4-bg6qs   1/1     Running   0          3d19h
minio-sandbox-console-6d67f645f4-ljrjh   1/1     Running   0          3d19h
minio-sandbox-zone-0-0                   1/1     Running   0          3d19h
minio-sandbox-zone-0-1                   1/1     Running   0          3d19h
minio-sandbox-zone-0-2                   1/1     Running   0          3d19h
minio-sandbox-zone-0-3                   1/1     Running   0          3d19h
$ oc minio tenant expand --name minio-sandbox --servers 4 --volumes 4 --capacity 1Ti --namespace minio
Adding new volumes to MinIO Tenant minio-sandbox
$ oc get pvc
NAME                       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
0-minio-sandbox-zone-0-0   Bound    pvc-db00aef2-a48d-4f36-8335-4c6fe4abb157   256Gi      RWO            thin           3d19h
0-minio-sandbox-zone-0-1   Bound    pvc-25acf08f-b4c9-4027-a090-dfdbbd1599c3   256Gi      RWO            thin           3d19h
0-minio-sandbox-zone-0-2   Bound    pvc-39b87ac0-5766-401e-9006-553259e1b768   256Gi      RWO            thin           3d19h
0-minio-sandbox-zone-0-3   Bound    pvc-de68af50-6980-4a57-ad8b-8463cd6a5bff   256Gi      RWO            thin           3d19h
0-minio-sandbox-zone-1-0   Bound    pvc-e7a575bb-c996-4541-8d8e-c09e1bb241c2   256Gi      RWO            thin           42s
0-minio-sandbox-zone-1-1   Bound    pvc-cfd41b17-34fa-4111-9263-c906c108c75f   256Gi      RWO            thin           42s
0-minio-sandbox-zone-1-2   Bound    pvc-76b3151c-44de-4cd6-8c7f-f94b3dbae5bc   256Gi      RWO            thin           42s
0-minio-sandbox-zone-1-3   Bound    pvc-c13b3ac5-9b4e-4dc8-9047-84584a6b2e13   256Gi      RWO            thin           42s
$ oc get pods
NAME                                     READY   STATUS    RESTARTS   AGE
minio-operator-5f7fd98c7d-xp9hd          1/1     Running   0          4d23h
minio-sandbox-console-6d67f645f4-bg6qs   1/1     Running   0          3d19h
minio-sandbox-console-6d67f645f4-ljrjh   1/1     Running   0          3d19h
minio-sandbox-zone-0-0                   1/1     Running   0          3d19h
minio-sandbox-zone-0-1                   1/1     Running   0          3d19h
minio-sandbox-zone-0-2                   1/1     Running   0          3d19h
minio-sandbox-zone-0-3                   1/1     Running   0          3d19h
minio-sandbox-zone-1-0                   1/1     Running   0          3m55s
minio-sandbox-zone-1-1                   1/1     Running   0          3m55s
minio-sandbox-zone-1-2                   1/1     Running   0          3m55s
minio-sandbox-zone-1-3                   1/1     Running   0          3m55s
$ oc logs minio-sandbox-zone-1-0

 You are running an older version of MinIO released 1 month ago
 Update: Run `mc admin update`


Waiting for the first server to format the disks.
Waiting for the first server to format the disks.
Waiting for the first server to format the disks.
Waiting for the first server to format the disks.
Waiting for the first server to format the disks.
Waiting for the first server to format the disks.
Waiting for the first server to format the disks.
Waiting for the first server to format the disks...`

**Comment by djfoley01** [comment] 2020-11-24 21:31
Before I did the expand, the first 4 nodes were working as expected and no issues were preset. As soon as I did the expand, the first zone now is not accessible, when I look at the statefulset, it shows "Phase: Pending" under volumeClaimTemplates. All of the pods show they are assign the correct volume, so I'm not really understanding where the problem is.

`I1124 16:09:42.479818       1 main-controller.go:773] Successfully synced 'minio/minio-sandbox'
I1124 16:10:12.484276       1 main-controller.go:773] Successfully synced 'minio/minio-sandbox'
I1124 16:10:42.478446       1 main-controller.go:773] Successfully synced 'minio/minio-sandbox'
I1124 16:10:47.964749       1 main-controller.go:970] Deploying zone zone-1
I1124 16:10:48.096645       1 main-controller.go:773] Successfully synced 'minio/minio-sandbox'
I1124 16:10:53.118171       1 main-controller.go:773] Successfully synced 'minio/minio-sandbox'
I1124 16:10:58.124855       1 main-controller.go:773] Successfully synced 'minio/minio-sandbox'`

The above is all there is in the operator logs. 

The first zone (Zone 0) logs from one container:

`oc logs minio-sandbox-zone-0-0

 You are running an older version of MinIO released 1 month ago
 Update: Run `mc admin update`


Waiting for a minimum of 2 disks to come online (elapsed 0s)

Waiting for a minimum of 2 disks to come online (elapsed 1s)

Waiting for all other servers to be online to format the disks.
Waiting for all other servers to be online to format the disks.
Formatting 1st zone, 1 set(s), 4 drives per set.
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Attempting encryption of all config, IAM users and policies on MinIO backend
All MinIO sub-systems initialized successfully
Waiting for all MinIO IAM sub-system to be initialized.. lock acquired
Status:         4 Online, 0 Offline.
Endpoint:  https://10.87.5.78:9000  https://127.0.0.1:9000

Browser Access:
   https://10.87.5.78:9000  https://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
data-crawl: No buckets found, skipping crawl
data-crawl: No buckets found, skipping crawl
data-crawl: No buckets found, skipping crawl
2020/11/20 20:56:26 http: TLS handshake error from 10.85.4.1:36406: remote error: tls: unknown certificate
2020/11/20 20:56:32 http: TLS handshake error from 10.85.4.1:36544: remote error: tls: unknown certificate
data-crawl: No buckets found, skipping crawl
2020/11/20 21:21:16 http: TLS handshake error from 10.85.4.1:43932: remote error: tls: unknown certificate
2020/11/20 21:25:55 http: TLS handshake error from 10.85.4.1:50354: remote error: tls: unknown certificate
Restarting on service signal

 You are running an older version of MinIO released 1 month ago
 Update: Run `mc admin update`


Waiting for all MinIO sub-systems to be initialized.. lock acquired
All MinIO sub-systems initialized successfully
Waiting for all MinIO IAM sub-system to be initialized.. lock acquired
Status:         4 Online, 0 Offline.
Endpoint:  https://10.87.5.78:9000  https://127.0.0.1:9000

Browser Access:
   https://10.87.5.78:9000  https://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide`

**Comment by harshavardhana** [comment] 2020-11-24 21:40
> 2020/11/20 20:56:26 http: TLS handshake error from 10.85.4.1:36406: remote error: tls: unknown certificate
> 2020/11/20 20:56:32 http: TLS handshake error from 10.85.4.1:36544: remote error: tls: unknown certificate
> data-crawl: No buckets found, skipping crawl
> 2020/11/20 21:21:16 http: TLS handshake error from 10.85.4.1:43932: remote error: tls: unknown certificate
> 2020/11/20 21:25:55 http: TLS handshake error from 10.85.4.1:50354: remote error: tls: unknown certificate

The actual issue

**Comment by djfoley01** [comment] 2020-11-24 22:04
@harshavardhana  That's not the issue, that went away after the CSR's were approved and that cluster was actually working. Those logs came from the working zone.

**Comment by djfoley01** [comment] 2020-11-25 03:29
I just attempted the expand on a completely separate Kubernetes 1.19.4 cluster using NFS instead of VMDKs. Using the latest operator:
kubectl minio init
kubectl minio tenant create --name minio --servers 2 --volumes 4 --capacity 100G
kubectl minio tenant expand --name minio --servers 2 --volumes 4 --capacity 100G

kubectl get pods | grep zone
minio-zone-0-0                    1/1     Running            0          22m
minio-zone-0-1                    1/1     Running            0          22m
minio-zone-1-0                    1/1     Running            0          11m
minio-zone-1-1                    1/1     Running            0          11m

kubectl get pvc
NAME               STATUS   VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
0-minio-zone-0-0   Bound    kube1    25G        RWO                           16m
0-minio-zone-0-1   Bound    kube4    25Gi       RWO                           15m
0-minio-zone-1-0   Bound    kube7    25Gi       RWO                           10m
0-minio-zone-1-1   Bound    kube9    25Gi       RWO                           10m
1-minio-zone-0-0   Bound    kube5    25Gi       RWO                           14m
1-minio-zone-0-1   Bound    kube2    25Gi       RWO                           13m
1-minio-zone-1-0   Bound    kube6    25Gi       RWO                           10m
1-minio-zone-1-1   Bound    kube8    25Gi       RWO                           10m


Exact same issue on the additional nodes, same message forever:
Waiting for the first server to format the disks.
Waiting for the first server to format the disks.
Waiting for the first server to format the disks.

**Comment by harshavardhana** [comment] 2020-11-25 03:31
> I just attempted the expand on a completely separate Kubernetes 1.19.4 cluster using NFS instead of VMDKs. Using the latest operator:
> kubectl minio init
> kubectl minio tenant create --name minio --servers 2 --volumes 4 --capacity 100G
> kubectl minio tenant expand --name minio --servers 2 --volumes 4 --capacity 100G
> 
> kubectl get pods | grep zone
> minio-zone-0-0 1/1 Running 0 22m
> minio-zone-0-1 1/1 Running 0 22m
> minio-zone-1-0 1/1 Running 0 11m
> minio-zone-1-1 1/1 Running 0 11m
> 
> kubectl get pvc
> NAME STATUS VOLUME CAPACITY ACCESS MODES STORAGECLASS AGE
> 0-minio-zone-0-0 Bound kube1 25G RWO 16m
> 0-minio-zone-0-1 Bound kube4 25Gi RWO 15m
> 0-minio-zone-1-0 Bound kube7 25Gi RWO 10m
> 0-minio-zone-1-1 Bound kube9 25Gi RWO 10m
> 1-minio-zone-0-0 Bound kube5 25Gi RWO 14m
> 1-minio-zone-0-1 Bound kube2 25Gi RWO 13m
> 1-minio-zone-1-0 Bound kube6 25Gi RWO 10m
> 1-minio-zone-1-1 Bound kube8 25Gi RWO 10m
> 
> Exact same issue on the additional nodes, same message forever:
> Waiting for the first server to format the disks.
> Waiting for the first server to format the disks.
> Waiting for the first server to format the disks.

AFAICS this issue is

**Comment by djfoley01** [comment] 2020-11-26 05:00
I fixed the issue at least for my kube 1.19.4 cluster, the issue was the statefulset for the first zone didn't get updated with the newest "ENDPOINTS":
Before:

kubectl edit statefulset minio-zone-0  
...
        - name: MINIO_ENDPOINTS
          value: https://minio-zone-0-{0...1}.minio-hl.default.svc.cluster.local/export{0...1}

After and confirmed working:

kubectl edit statefulset minio-zone-0  
...
        - name: MINIO_ENDPOINTS  
          value: https://minio-zone-0-{0...1}.minio-hl.default.svc.cluster.local/export{0...1}  
            https://minio-zone-1-{0...1}.minio-hl.default.svc.cluster.local/export{0...1}

Logs from the previously not functioning zone:

Waiting for the first server to format the disks.
Waiting for the first server to format the disks.
Waiting for the first server to format the disks.
Waiting for all MinIO sub-systems to be initialized.. lock acquired
All MinIO sub-systems initialized successfully
Waiting for all MinIO IAM sub-system to be initialized.. lock acquired
Status:         8 Online, 0 Offline.
Endpoint:  https://10.42.1.11:9000  https://127.0.0.1:9000

Browser Access:
   https://10.42.1.11:9000  https://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide

I'll validate the issue is resolved by manually modifying the statefulset env variable on my openshift 4.6.4 cluster tomorrow, but I believe it's the same issue.

**Comment by cyluss** [comment] 2020-12-01 09:07
@djfoley01 Working fine on TKG, after modifying MINIO_ENDPOINTS env variable

**Comment by nitisht** [comment] 2020-12-29 06:27
closing this based on above comments.

**Closed by nitisht** 2020-12-29 06:27 UTC

**Comment by stanleycyk** [comment] 2022-07-21 11:18
> I fixed the issue on both clusters, the issue was the statefulset for the first zone didn't get updated with the newest "ENDPOINTS" when the new zone was created. After the new nodes for the new zone have come up and are running, you just have to go add the additional endpoints to the first zone manually:
> 
> Before:
> 
> kubectl edit statefulset minio-zone-0 ... - name: MINIO_ENDPOINTS value: [https://minio-zone-0-{0...1}.minio-hl.default.svc.cluster.local/export{0...1}](https://minio-zone-0-%7B0...1%7D.minio-hl.default.svc.cluster.local/export%7B0...1%7D)
> 
> After and confirmed working:
> 
> kubectl edit statefulset minio-zone-0 ... - name: MINIO_ENDPOINTS value: [https://minio-zone-0-{0...1}.minio-hl.default.svc.cluster.local/export{0...1}](https://minio-zone-0-%7B0...1%7D.minio-hl.default.svc.cluster.local/export%7B0...1%7D) [https://minio-zone-1-{0...1}.minio-hl.default.svc.cluster.local/export{0...1}](https://minio-zone-1-%7B0...1%7D.minio-hl.default.svc.cluster.local/export%7B0...1%7D)
> 
> Logs from the previously not functioning zone:
> 
> Waiting for the first server to format the disks. Waiting for the first server to format the disks. Waiting for the first server to format the disks. Waiting for all MinIO sub-systems to be initialized.. lock acquired All MinIO sub-systems initialized successfully Waiting for all MinIO IAM sub-system to be initialized.. lock acquired Status: 8 Online, 0 Offline. Endpoint: https://10.42.1.11:9000 https://127.0.0.1:9000
> 
> Browser Access: https://10.42.1.11:9000 https://127.0.0.1:9000
> 
> Object API (Amazon S3 compatible): Go: https://docs.min.io/docs/golang-client-quickstart-guide Java: https://docs.min.io/docs/java-client-quickstart-guide Python: https://docs.min.io/docs/python-client-quickstart-guide JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide .NET: https://docs.min.io/docs/dotnet-client-quickstart-guide

Saved my day, cheers!!!
