### ISSUE TITLE
PVC in pending status when deploying a tenant

### ISSUE THREAD

**Issue by passadoreg** [minio/operator#1189] opened 2022-06-30 18:23 UTC
Hi all, I'm trying to deploy a simple single node tenant, already deployed Minio using helm.

I created this local storage class:
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

Since I have two nodes, I created a PV on each one like this:
apiVersion: v1
kind: PersistentVolume
metadata:
   name: minio-local-pv1
spec:
   capacity:
      storage: 40Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: local-storage
   local:
      path: /media/local-storage
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - nucworker

I'm trying to deploy the tenant using this yml:
## Secret to be used as MinIO Root Credentials
apiVersion: v1
kind: Secret
metadata:
  namespace: minio-tenant
  name: minio-autocert-no-encryption-minio-creds-secret
type: Opaque
data:
  ## Access Key for MinIO Tenant, base64 encoded (echo -n 'minio' | base64)
  accesskey: bWluaW8=
  ## Secret Key for MinIO Tenant, base64 encoded (echo -n 'minio123' | base64)
  secretkey: bWluaW8xMjM=
---
## Secret to be used for MinIO Console
apiVersion: v1
kind: Secret
metadata:
  namespace: minio-tenant
  name: minio-autocert-no-encryption-console-secret
type: Opaque
data:
  ## Passphrase to encrypt jwt payload, base64 encoded (echo -n 'SECRET' | base64)
  CONSOLE_PBKDF_PASSPHRASE: U0VDUkVU
  ## Salt to encrypt jwt payload, base64 encoded (echo -n 'SECRET' | base64)
  CONSOLE_PBKDF_SALT: U0VDUkVU
  ## MinIO User Access Key (used for Console Login), base64 encoded (echo -n 'YOURCONSOLEACCESS' | base64)
  CONSOLE_ACCESS_KEY: WU9VUkNPTlNPTEVBQ0NFU1M=
  ## MinIO User Secret Key (used for Console Login), base64 encoded (echo -n 'YOURCONSOLESECRET' | base64)
  CONSOLE_SECRET_KEY: WU9VUkNPTlNPTEVTRUNSRVQ=
---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: storage
  namespace: minio-tenant
spec:
  ## Secret with credentials to be used by MinIO Tenant.
  ## Refers to the secret object created above.
  credsSecret:
    name: minio-autocert-no-encryption-minio-creds-secret
  ## Specification for MinIO Pool(s) in this Tenant.
  pools:
    ## Servers specifies the number of MinIO Tenant Pods / Servers in this pool.
    ## For standalone mode, supply 1. For distributed mode, supply 4 or more.
    ## Note that the operator does not support upgrading from standalone to distributed mode.
    - servers: 1
      ## custom pool name
      name: pool-0
      ## volumesPerServer specifies the number of volumes attached per MinIO Tenant Pod / Server.
      volumesPerServer: 4
      ## This VolumeClaimTemplate is used across all the volumes provisioned for MinIO Tenant in this Pool.
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: local-storage

Deployment gets stuck on provisioning the PVC. I tested with a sample PVC and an Nginx deployment and the binding completes successfully.

Anything missing?

**Comment by allanrogerr** [comment] 2023-11-15 01:15
Im unable to reproduce this. Please take a look at the steps I followed and try again using the latest minio operator release.
https://github.com/allanrogerr/public/wiki/minio-%E2%80%90-tenant-%E2%80%90-setup-with-persistentvolume

**Comment by allanrogerr** [comment] 2023-11-28 12:18
@passadoreg Are you still facing this issue on the latest minio operator release v5.0.11?

**Comment by passadoreg** [comment] 2023-11-28 12:25
Just dropped using Minio by now, will test again in the future.

**Comment by allanrogerr** [comment] 2023-11-29 12:03
Before closing, please ensure you have enough space before instructing the tenant to attempt to generate pvcs. Let us know if this occurs again.

**Closed by allanrogerr** 2023-11-29 12:03 UTC
Labels: community, triage
