### ISSUE TITLE
Access to the minio browser/console

### ISSUE THREAD

**Issue by fcomte** [minio/operator#716] opened 2021-07-09 21:22 UTC
**Is your feature request related to a problem? Please describe.**

The console port is randomly generate and there is no service pointing to it.
We can't access with openid to the web ui.

**Describe the solution you'd like**
I would like to be able to create a tenant that can expose the randomly (or fixed) port to a kubernetes service in order to publish it.

**Comment by dnskr** [comment] 2021-07-09 21:30
What's the docker image version you use?

**Comment by fcomte** [comment] 2021-07-09 21:49
I using the last docker image RELEASE.2021-07-08T01-15-01Z

**Comment by fcomte** [comment] 2021-07-09 21:55
and  minio/operator:v4.1.1

**Comment by dnskr** [comment] 2021-07-09 21:59
Try to use RELEASE.2021-06-17T00-10-46Z instead.
The issue might be related to my [comment](https://github.com/minio/operator/issues/715#issuecomment-877119939)

**Comment by fcomte** [comment] 2021-07-09 22:06
i had no problem with this one

**Comment by dnskr** [comment] 2021-07-09 22:10
Am I right that you cannot reproduce the issue with minio/operator:v4.1.1 and docker image RELEASE.2021-06-17T00-10-46Z ?

**Comment by fcomte** [comment] 2021-07-09 22:28
yes

**Comment by fcomte** [comment] 2021-07-09 23:54
I don't think it's related. Redirect browser access is the new behaviour of minio. This is documented in the release.
But I think we can't publish this console with this operator at the moment

**Comment by harshavardhana** [comment] 2021-07-12 21:08
Operator does not yet support latest MinIO release - use the one that comes default with operator.

**Comment by fcomte** [comment] 2021-07-12 21:10
can you we use openid authentification ?

**Comment by fcomte** [comment] 2021-07-12 21:10
I was testing OPA , the issue you solved recently.

**Comment by harshavardhana** [comment] 2021-07-12 21:21
> I was testing OPA , the issue you solved recently.

If you want to use the latest @fcomte read about newer considerations 

https://github.com/minio/minio#test-using-minio-console

Until operator is changed to support latest MinIO you will have to stick to the one that comes default.

**Comment by fcomte** [comment] 2021-07-12 21:25
It's exactly what I look for. I did not find this environment variable friday. Thx

**Comment by fcomte** [comment] 2021-07-12 21:26
Just to let you know. I confirm that OPA is now working with the last release (btw)

**Comment by fcomte** [comment] 2021-07-12 21:31
I was looking to choose the redirect port  or to modify the command line to add --console-address to create the kubernetes svc and ingress myself. I will wait for the operator.

**Comment by harshavardhana** [comment] 2021-07-12 21:33
> I was looking to choose the redirect port or to modify the command line to add --console-address to create the kubernetes svc and ingress myself. I will wait for the operator.

yes, that part is not done, unfortunately, not sure if OPA will work as well with embedded console @fcomte as you already know OPA is the least of our priorities. 

We do have addressed the more fine-grained policy requirements by supporting more extended policies.

**Comment by fcomte** [comment] 2021-07-12 21:35
yes I know. I was looking about the consequence on the console side :)

**Comment by fcomte** [comment] 2021-07-12 21:36
I will test the extended policy. Do you have documentation about what is supported now ?

**Comment by harshavardhana** [comment] 2021-07-12 21:40
> I will test the extended policy. Do you have documentation about what is supported now ?

We will update that soon @fcomte mainly what is now supported is https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_multi-value-conditions.html

**Comment by fcomte** [comment] 2021-07-12 21:41
thx i will test soon

**Comment by fcomte** [comment] 2021-07-13 13:07
Still using the operator, I create a custom service using the random port and ingress.
I follow your advice @harshavardhana by using MINIO_BROWSER_REDIRECT_URL

The redirection is now working but ... I am using keycloak and the redirect uri created by the console does not use this information to create the redirect uri.

**Comment by kannappanr** [comment] 2021-07-21 07:16
Closing this issue as answered, please feel free to reach out to us if you have further questions

**Closed by kannappanr** 2021-07-21 07:16 UTC

**Comment by fcomte** [comment] 2021-08-06 07:12
> Operator does not yet support latest MinIO release - use the one that comes default with operator.

Is there any ETA for this feature ?
