### ISSUE TITLE
Operator fails to create secret operator-tls

### ISSUE THREAD

**Issue by dkhachyan** [minio/operator#506] opened 2021-03-02 20:58 UTC
Operator fails to create TLS secret

```
I0302 20:12:01.761690       1 main.go:72] Starting MinIO Operator
I0302 20:12:02.230727       1 main.go:139] caBundle on CRD updated
I0302 20:12:02.231779       1 main-controller.go:250] Setting up event handlers
I0302 20:12:02.231918       1 main-controller.go:634] Starting Tenant controller
I0302 20:12:02.231928       1 main-controller.go:637] Waiting for informer caches to sync
I0302 20:12:02.263090       1 main-controller.go:598] operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)
E0302 20:12:02.291766       1 operator.go:112] Unexpected error during the creation of the csr/operator-minio-operator-csr: certificatesigningrequests.certificates.k8s.io "operator-minio-operator-csr" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion minio.min.io/v2 Kind Tenant: no matches for kind "Tenant" in version "minio.min.io/v2"
I0302 20:12:02.291835       1 main-controller.go:601] Waiting for the operator certificates to be issued certificatesigningrequests.certificates.k8s.io "operator-minio-operator-csr" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion minio.min.io/v2 Kind Tenant: no matches for kind "Tenant" in version "minio.min.io/v2"
I0302 20:12:02.732175       1 main-controller.go:642] Starting workers
I0302 20:12:12.298838       1 main-controller.go:598] operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)
E0302 20:12:12.308273       1 operator.go:112] Unexpected error during the creation of the csr/operator-minio-operator-csr: certificatesigningrequests.certificates.k8s.io "operator-minio-operator-csr" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion minio.min.io/v2 Kind Tenant: no matches for kind "Tenant" in version "minio.min.io/v2"
I0302 20:12:12.308356       1 main-controller.go:601] Waiting for the operator certificates to be issued certificatesigningrequests.certificates.k8s.io "operator-minio-operator-csr" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion minio.min.io/v2 Kind Tenant: no matches for kind "Tenant" in version "minio.min.io/v2"
I0302 20:12:22.317267       1 main-controller.go:598] operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)
I0302 20:12:22.377467       1 csr.go:217] Start polling for certificate of csr/operator-minio-operator-csr, every 5s, timeout after 20m0s
I0302 20:12:27.385519       1 csr.go:242] Certificate successfully fetched, creating secret with Private key and Certificate
E0302 20:12:27.389093       1 operator.go:129] Unexpected error during the creation of the secret/operator-tls: secrets "operator-tls" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion minio.min.io/v2 Kind Operator: no matches for kind "Operator" in version "minio.min.io/v2"
I0302 20:12:27.389155       1 main-controller.go:601] Waiting for the operator certificates to be issued secrets "operator-tls" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion minio.min.io/v2 Kind Operator: no matches for kind "Operator" in version "minio.min.io/v2"
I0302 20:12:37.393981       1 main-controller.go:598] operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)
```

## Expected Behavior
Tenant created

## Current Behavior
Operator successfully creates CertificateSigningRequests but could not create secret.
```
oc get csr
NAME                          AGE   SIGNERNAME                     REQUESTOR                                             CONDITION
operator-minio-operator-csr   43m   kubernetes.io/legacy-unknown   system:serviceaccount:minio-operator:minio-operator   Approved,Issued
```

Tenant creation fails

## Your Environment
* minio-operator: 4.0.0
* OpenShift 4.5/Kubernetes 1.18

**Comment by Alevsk** [comment] 2021-03-03 02:25
@dkhachyan Hi, do you see any secret generation related error on `kubectl get events --all-namespaces` ?, also can you `kubectl get csr operator-minio-operator-csr -o yaml` and verify the certificate was issued correctly under `Status.Certificate` field?

**Comment by dkhachyan** [comment] 2021-03-03 05:31
kubectl get events --all-namespaces - does not show any secret generation errors


kubectl get csr operator-minio-operator-csr -o yaml

```
status:
  certificate: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMzVENDQWNXZ0F3SUJBZ0lSQUtCYnYxQ3dST0k3L2dKMW1MdlZsclV3RFFZSktvWklodmNOQVFFTEJRQXcKSmpFa01DSUdBMVVFQXd3YmEzVmlaUzFqYzNJdGMybG5ibVZ5WDBBeE5qRTBNREExTWpjMk1CNFhEVEl4TURNdwpNekF6TVRReE5Wb1hEVEl4TURNeU5ERTBORGMxTjFvd09ERVFNQTRHQTFVRUNoTUhRV050WlNCRGJ6RWtNQ0lHCkExVUVBeE1iYjNCbGNtRjBiM0l1YldsdWFXOHRiM0JsY21GMGIzSXVjM1pqTUZrd0V3WUhLb1pJemowQ0FRWUkKS29aSXpqMERBUWNEUWdBRWRaQjdhbzFhdFdYQzcweS9sK1RhMVZqS3lINFZ0VU5RUURkN1Y1V1E4UG4rb0tDYgpnMU5pSVZIVFliSnRLRU52eCtMQ1lqeGcxTnFiUytnY2Jvd3FMS09CdmpDQnV6QU9CZ05WSFE4QkFmOEVCQU1DCkI0QXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXcKSHdZRFZSMGpCQmd3Rm9BVVhMbE5QZFk4T0EzcnR6QmFwTGw4aUFTcGdPd3dXd1lEVlIwUkJGUXdVb0lJYjNCbApjbUYwYjNLQ0cyOXdaWEpoZEc5eUxtMXBibWx2TFc5d1pYSmhkRzl5TG5OMlk0SXBiM0JsY21GMGIzSXViV2x1CmFXOHRiM0JsY21GMGIzSXVjM1pqTG1Oc2RYTjBaWEl1Ykc5allXd3dEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUIKQUV2dUZmeHZncmEra1FjYWtiVk5jK0hlQnc1eUFna2MxRFJOc2Y1Vy9weUtjbndReENSMVVaMFZGRUxwQ2R0MwpnczZ4RjRadG5mVnRBV3JrMUxZSEhYTnFFcit3NDVxU0hqbEdOWnpDUkJ5N0EwdUg0TW5LOFRoTGJFTWdKN3hhCmNyODVRUUJtZEJmK0tYSFFCTm80RXRKQWRBWUVZRG55MkpSbERINEd2WXM5WXpmQVFBdlNnR2ZKNXNHQ21GZUkKN2d6YkJ5eUhCVzNtcTJXZVFYdTV4OW0wNmU4T3FhZytaVnc0eTlUSHUveTI4eEwwNG5vK3l1NExISUU3WTQzcQpWUDlrN2c1VWxmNnZscndOeFhDS3lPRFNoZTRGNHhIcW1HVzhjTDBHZ2ZqWTVCc1hZNkJ5SXkxV2VpWVRjem9DCkdITHJPRGxzTWtUTjdJbURuZ3Uxd0dNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  conditions:
  - lastUpdateTime: "2021-03-03T03:19:16Z"
    message: Automatically approved by MinIO Operator
    reason: MinIOOperatorAutoApproval
    type: Approved
```

Operator tries to create secret here:
```
func (c *Controller) createOperatorTLSSecret(ctx context.Context, operator metav1.Object, labels map[string]string, secretName string, pkBytes, certBytes []byte) error {
	secret := &corev1.Secret{
		Type: "Opaque",
		ObjectMeta: metav1.ObjectMeta{
			Name:      secretName,
			Namespace: miniov2.GetNSFromFile(),
			Labels:    labels,
			OwnerReferences: []metav1.OwnerReference{
				*metav1.NewControllerRef(operator, schema.GroupVersionKind{
					Group:   miniov2.SchemeGroupVersion.Group,
					Version: miniov2.SchemeGroupVersion.Version,
					Kind:    miniov2.OperatorCRDResourceKind,
				}),
			},
		},
		Data: map[string][]byte{
			"private.key": pkBytes,
			"public.crt":  certBytes,
		},
	}
	_, err := c.kubeClientSet.CoreV1().Secrets(miniov2.GetNSFromFile()).Create(ctx, secret, metav1.CreateOptions{})
	return err
}
```

Maybe something wrong with Kind:  miniov2.OperatorCRDResourceKind, because I can't find kind: Operator in minio crd

**Comment by nitisht** [comment] 2021-03-03 05:37
Would you be open to testing custom operator images if we provide those here?

**Comment by dkhachyan** [comment] 2021-03-03 05:41
Yes of course!

**Comment by nitisht** [comment] 2021-03-03 09:04
can you try this operator image `nitishtiwari/operator:edge12` . Keep everything else same.

**Comment by dkhachyan** [comment] 2021-03-03 14:16
Operator successfully creates operator-tls secret with this image
Tenant also creates fine, but there are some TLS handshake errors in operator logs
```
I0303 13:51:36.125464       1 main.go:72] Starting MinIO Operator
I0303 13:51:36.806693       1 main.go:139] caBundle on CRD updated
I0303 13:51:36.807340       1 main-controller.go:250] Setting up event handlers
I0303 13:51:36.807414       1 main-controller.go:634] Starting Tenant controller
I0303 13:51:36.807420       1 main-controller.go:637] Waiting for informer caches to sync
I0303 13:51:36.845149       1 main-controller.go:625] Starting api server
I0303 13:51:37.207664       1 main-controller.go:642] Starting workers
2021/03/03 14:08:03 http: TLS handshake error from 10.253.0.1:36176: remote error: tls: bad certificate
2021/03/03 14:08:03 http: TLS handshake error from 10.253.32.1:53688: remote error: tls: bad certificate
2021/03/03 14:08:04 http: TLS handshake error from 10.253.0.1:36190: remote error: tls: bad certificate
2021/03/03 14:08:04 http: TLS handshake error from 10.253.32.1:53704: remote error: tls: bad certificate
2021/03/03 14:08:05 http: TLS handshake error from 10.253.0.1:36204: remote error: tls: bad certificate
2021/03/03 14:08:05 http: TLS handshake error from 10.253.32.1:53712: remote error: tls: bad certificate
2021/03/03 14:08:06 http: TLS handshake error from 10.253.0.1:36232: remote error: tls: bad certificate
2021/03/03 14:08:06 http: TLS handshake error from 10.253.32.1:53720: remote error: tls: bad certificate
2021/03/03 14:08:07 http: TLS handshake error from 10.253.0.1:36246: remote error: tls: bad certificate
2021/03/03 14:08:07 http: TLS handshake error from 10.253.32.1:53726: remote error: tls: bad certificate
2021/03/03 14:08:08 http: TLS handshake error from 10.253.0.1:36252: remote error: tls: bad certificate
2021/03/03 14:08:08 http: TLS handshake error from 10.253.32.1:53740: remote error: tls: bad certificate
```

**Comment by nitisht** [comment] 2021-03-03 14:41
Thanks @dkhachyan this is helpful

**Comment by titou10titou10** [comment] 2021-03-03 17:07
Same error with OpenShift v 4.6.18

**Comment by titou10titou10** [comment] 2021-03-04 01:30
Found this in the [operator SDK FAQ](https://sdk.operatorframework.io/docs/faqs/#i-keep-hitting-errors-like-is-forbidden-cannot-set-blockownerdeletion-if-an-ownerreference-refers-to-a-resource-you-cant-set-finalizers-on-how-do-i-fix-this) about the "*cannot set blockOwnerDeletion*" : 

> **I keep hitting errors like “is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can’t set finalizers on:”, how do I fix this?**
if you are facing this issue, it means that the operator is missing the required RBAC permissions to update finalizers on the APIs it manages. This permission is necessary if the OwnerReferencesPermissionEnforcement plugin is enabled in your cluster.
> 
> For Helm and Ansible operators, this permission is configured by default. However for Go operators, it may be necessary to add this permission yourself by adding an RBAC directive to generate a config/rbac/role.yaml with update privileges on your CR’s finalizers:*
> 
>     // +kubebuilder:rbac:groups=cache.example.com,resources=memcacheds/finalizers,verbs=update*

**Comment by nitisht** [comment] 2021-03-04 07:08
@titou10titou10 can you try adding this in the operator RBAC and let us know how ti goes?

**Comment by nitisht** [comment] 2021-03-04 07:16
closing this as duplicate of #496 . Let's continue discussion there.

**Closed by nitisht** 2021-03-04 07:16 UTC

**Comment by titou10titou10** [comment] 2021-03-04 13:40
@nitisht I think this is not the problem as the`minio-operator-role`cluster role assigned to the serviceaccount already has all rights on all resources in schema`minio.mim.io`

    - apiGroups:
      - minio.min.io
      resources:
      - "*"
      verbs:
      - "*"

The "cannot set blockOwnerDeletion" is a consequence of the non creation of the tls secret because the owner of kind "miniov2.OperatorCRDResourceKind" does not exists as explained earlier by @dkhachyan 
Solving this issue will solve the other issue

and FYI using image`nitishtiwari/operator:edge12`works for me with the same messages already noticed by @dkhachyan 

    TLS handshake error from xx.xx.xx.xx:xxxxx: remote error: tls: bad certificate

Sorry for the noise
