### ISSUE TITLE
Pod Rolling Restart and Sidecar Readiness Probe Failure after Upgrading from v5.0.15 to v5.0.16

### ISSUE THREAD

**Issue by fengyinqiao** [minio/operator#2198] opened 2024-07-04 13:01 UTC
**Description:**
After upgrading MinIO Operator from version v5.0.15 to v5.0.16, all existing tenant pods underwent a rolling restart. Additionally, the sidecar container readiness probe consistently failed. Upon checking the sidecar logs, the only message displayed was "Starting Sidecar," and no further logs were generated, indicating that the startup process might be stuck.

**Steps to Reproduce:**
1. Upgrade MinIO Operator from v5.0.15 to v5.0.16.
2. Observe the tenant pods' behavior.
3. Check the sidecar container logs.

**Observed Behavior:**
1. All tenant pods restarted.
2. Sidecar container readiness probes failed.
3. Sidecar logs only displayed "Starting Sidecar" without further output.

**Expected Behavior:**
1. Tenant pods should not undergo unnecessary rolling restarts.
2. Sidecar containers should start correctly and pass readiness probes.

**Commands Used:**
```bash
➜  Downloads kperf -n minio-operator get pod  -w
NAME                              READY   STATUS    RESTARTS   AGE
minio-test-pool-0-0               2/2     Running   0          168m
minio-test-pool-0-1               2/2     Running   0          168m
minio-test-pool-0-2               2/2     Running   0          168m
minio-test-pool-0-3               1/2     Running   0          2m57s

➜  Downloads kperf -n minio-operator logs minio-test-pool-0-3 -c sidecar
2024/07/04 12:38:38 sidecar_utils.go:51: Starting Sidecar
```

**Issues Identified:**
1. The upgrade process updates the sidecar container image in the sts template (`sts.spec.template.containers[1].image`), triggering a rolling restart of all existing pods. Please confirm if this behavior is expected.
2. Investigate why the sidecar container startup is stuck.
3. The default sidecar image is not available on Docker Hub:
```bash
➜  Downloads docker pull --platform=linux/amd64 minio/operator-sidecar:edge
Error response from daemon: pull access denied for minio/operator-sidecar, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Additional Information:**
- Kubernetes Version: 1.22.15
- MinIO Operator Version: v5.0.16

Thank you for your assistance in resolving these issues.

**Comment by harshavardhana** [comment] 2024-07-04 14:50
v5.0.15 and v5.0.16 are the same release, we re-released it to rebuild our containers. Not sure why you were upgrading. 

> ```shell
> ➜  Downloads docker pull --platform=linux/amd64 minio/operator-sidecar:edge
> Error response from daemon: pull access denied for minio/operator-sidecar, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
> ```

There is no such thing as `:edge` image referenced anywhere in the code-base, looks like you did some custom work here.

It looks like you tried to build something locally and botched your deployment. Closing this as not reproducible and an environmental issue on your end.

**Closed by harshavardhana** 2024-07-04 14:50 UTC
Labels: community, triage

**Comment by harshavardhana** [comment] 2024-07-04 15:54
v5.0.16 is unpublished, revert to v5.0.15 - v5.0.16 will be republished properly it looks like some assets were not updated properly.

**Comment by fengyinqiao** [comment] 2024-07-05 02:17
I used the latest code from the master branch, built and updated the image myself, and then updated the CRD file pointed to by kustomization.yaml to k8s. The problem is easy to repeat. You can try it. 
Causes of the pod rolling restart here, ` sts.spec.template.containers[1].image` forced updated, please confirm whether this behavior is reasonable @harshavardhana :
https://github.com/minio/operator/pull/2105/files#diff-dd388a34c55183c615d3aed4bb2004c13ad10d64c2163370890a0746b00cd707R915

**Comment by fengyinqiao** [comment] 2024-07-05 02:20
> There is no such thing as `:edge` image referenced anywhere in the code-base, looks like you did some custom work here.

@harshavardhana  see here:
https://github.com/minio/operator/pull/2105/files#diff-6ea7c09207758c5dbbe78e214073fe4428f1853543ddd26fb47d99ee26cc9774R26

**Comment by chancez** [comment] 2024-07-24 16:20
I'm hitting this issue where the sidecar starts but never becomes ready on a fresh install of 6.0.1 in our CI as well.

**Comment by chancez** [comment] 2024-07-24 16:27
Actually I think I figured it out: It's probably because we're using TLS:

https://github.com/minio/operator/blob/master/sidecar/pkg/sidecar/probes_handlers.go#L64 hardcodes the port to 9000 but the minio server listens on port 9443 when TLS is enabled. The sidecar needs to be configured to use the correct port when TLS is configured.

**Comment by fengyinqiao** [comment] 2024-07-25 03:10
> hardcodes the port to 9000

@chancez 
That should be the problem. Last time, I couldn't find the reason and this issue was forcibly closed!
